### ISSUE TITLE
Cannot create inference config with an environment that has additional R packages

### ISSUE THREAD

**Issue by heemanshusuri** [Azure/azureml-sdk-for-r#101]
**To Reproduce**
create an environment with R packages:
r_env <- r_environment(name = "myenv", cran_packages = c("ggplot2"))

create inference config
config <- inference_config(entry_script = "score.R", source_directory = ".", environment = r_env)

**Expected behavior**
an inference config object should be created

**Screenshots**
![bug](https://user-images.githubusercontent.com/51678909/66524474-69fae880-eaa7-11e9-8487-84c48a1a356c.png)

**Comment by ninghu** [comment]
The issue has been address in latest R SDK code.

**Comment by Narsi-1310** [comment]
This issue still persists, updated both azuremlsdk for python and r.

**Comment by heemanshusuri** [comment]
The python SDK version should be greater than "1.0.69". You can check it by running this command:
`azureml$core$"__version__"`

To install the latest version, run:
`azuremlsdk::install_azureml(version = "1.0.74")`

You should be able to use custom environment with R packages in your inference config.
