### ISSUE TITLE
optparse not included in default image

### ISSUE THREAD

**Issue by revodavid** [Azure/azureml-sdk-for-r#112]
**Describe the bug**
When an experiment is processed, we can see that the `getopt` package is being installed. Since every training script requires this package, this unneccessarily slows down training.

**To Reproduce**
```
run <- submit_experiment(exp, est)
view_run_details(run)
wait_for_run_completion(run, show_output = TRUE)
```

The output includes:
```
> install.packages('optparse', repos = 'http://cran.us.r-project.org')
also installing the dependency ‘getopt’
```

**Expected behavior**
The `getopt` package should already be installed in the image so that this step can be skipped.

**Comment by ninghu** [comment]
Resolved by #126
