### ISSUE TITLE
package e1071 is required

### ISSUE THREAD

**Issue by revodavid** [Azure/azureml-sdk-for-r#115]
**Describe the bug**
Training script fails with the error:
```
Error: package e1071 is required
Execution halted
```
As far as I can tell I am not using any function from e1071, and so it was not included in the `cran_packages` option to  `estimator`. Adding `"e1071"` to `cran_packages` works around the issue.

**To Reproduce**
https://github.com/revodavid/azure-ml-R-tutorial/tree/77f1f5b34d033764c410ef78921a1d46767a843f

**Expected behavior**
If `e1071` is always required, it should be loaded by default or documented as such. It's an odd dependency to have.

**Comment by ninghu** [comment]
Hi @revodavid , The link you provided gives me a 404.
https://github.com/revodavid/azure-ml-R-tutorial/tree/77f1f5b34d033764c410ef78921a1d46767a843f

**Comment by mx-iao** [comment]
package `e1071` is required by `caret`. `caret` is in our default base image but `e1071` is not; we will track this as an enhancement to add to base image.
