### ISSUE TITLE
Strange named component "datatables htmlwidget" in run viewer

### ISSUE THREAD

**Issue by revodavid** [Azure/azureml-sdk-for-r#117]
**Describe the bug**
Using `view_run_details` within an R Markdown chunk creates two "tabs", "datatables htmlwidget" and "R Console". The second name makes sense but the first is confusing.

**To Reproduce**
See screenshot

**Expected behavior**
"Azure ML Run Log" might be a better name.

**Screenshots**
![image](https://user-images.githubusercontent.com/152948/66872467-f2233700-ef5a-11e9-93d2-879555ca20b9.png)

**Additional context**
It's possible the "datatables htmlwidget" name is created by RStudio itself.

**Comment by ninghu** [comment]
datatables is the name of the htmlwidget we are using for rendering the run details. As you said, those names are created by RStudio so we are unable to rename to something else.
