### ISSUE TITLE
deploy-to-local sample get permission denied error when run on notebook vm

### ISSUE THREAD

**Issue by ninghu** [Azure/azureml-sdk-for-r#149]
**Describe the bug**
deploy-to-local sample get permission denied error when run on notebook vm

**To Reproduce**
service <- deploy_model(ws, 
                         'rservice-local', 
                         list(model), 
                         inference_config, 
                         local_deployment_config)
ERROR - Failed to create Docker client. Is Docker running/installed?
When you deploy locally, we download a dockerfile
execute docker build on it, and docker run the built container for you
Error: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  WebserviceException: WebserviceException:
	Message: Failed to create Docker client. Is Docker running/installed?
When you deploy locally, we download a dockerfile
execute docker build on it, and docker run the built container for you
Error: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Failed to create Docker client. Is Docker running/installed?\nWhen you deploy locally, we download a dockerfile\nexecute docker build on it, and docker run the built container for you\nError: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))"
    }
} 

**Expected behavior**
Shouldn't get any error for local deployment.

**Comment by AbeOmor** [comment]
In order to run this demo, you have to have root access to Docker. 
 If you are using Notebook VM you may get a "PermissionError(13, 'Permission denied'))" error,
because you may not have root access.
To add enable root access to Docker please, open the Terminal and run the following commands:
```
sudo usermod -a -G docker $USER
newgrp docker
```
 After running the following commands, restart your Notebook VM to be grant root permissions

**Comment by ninghu** [comment]
The notebook VM fix is rolling out to prod regions.

**Comment by virvirlopez** [comment]
Hi Ninghu, I have the same problem, can you explain better what did you do? Thanks!
