### ISSUE TITLE
Blank page for News on documentation site

### ISSUE THREAD

**Issue by ninghu** [Azure/azureml-sdk-for-r#158]
**Describe the bug**
Blank page for News on documentation site

**To Reproduce**
1. Go to https://azure.github.io/azureml-sdk-for-r/
2. Click on News

**Expected behavior**
The release notes should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/11171669/67608205-14c40580-f73c-11e9-800f-14fe0d605fa7.png)

**Comment by mx-iao** [comment]
Addressed by #160
