### ISSUE TITLE
[PROPOSAL] Versioning of SDK

### ISSUE THREAD

**Issue by csteegz** [Azure/azureml-sdk-for-r#162]
I'm concerned it can be very difficult for DRI's to debug/support this SDK. We've had multiple issues in the python SDK where the particular version is important to supporting the issues. For instance, sdk versions 1.0.57-1.0.62 were broken for uploading large models. 

I'd like to propose:

1. Plan to 'release' the R sdk on the same schedule as the python SDK going forward.
2. Version the R SDK like the python SDK
3. Hard code version in https://github.com/Azure/azureml-sdk-for-r/blob/master/R/install.R to default to installing the python SDK version which matches the R SDK version.

At the very least, I think 3 would be super helpful. If we move away from the Reticulate-style SDK, we can bump to 2.0 and switch to a sane versioning scheme.

**Comment by ninghu** [comment]
@csteegz thanks for the great suggestions. 

1. Currently R SDK is still under preview so we will continue to use version start with "0.". We do plan to match with python SDK version after it's GAed. 
2. Can't agree more on 3. This change will be made very soon.

**Comment by csteegz** [comment]
@ninghu what you say on 1 makes sense. Maybe we can have the last number of the version number correspond to the python SDK, since they're all versioned as 1.0.x?
