### ISSUE TITLE
Proxy - self signed certificate - unable to use SDK methods

### ISSUE THREAD

**Issue by ashley-betts70** [Azure/azureml-sdk-for-r#210]
**Describe the bug**
When running behind a corporate proxy that is terminating the ssl session and presenting a self signed certificate we are unable to use the sdk components.

**To Reproduce**

- Have initiating R session behind proxy that is presenting self signed certificate.
- Try to invoke a method such as get_default_datastore()

**Expected behavior**

- The ability to trust the self signed certificate (preferred) or
- Disable verification of presented certificate (obviously risky)

**Screenshots**
```
ds <- get_default_datastore(ws)
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  SSLError: HTTPSConnectionPool(host='centralus.experiments.azureml.net', port=443): Max retries exceeded with url: /discovery (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)'))) 
3.
stop(structure(list(message = "SSLError: HTTPSConnectionPool(host='centralus.experiments.azureml.net', port=443): Max retries exceeded with url: /discovery (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available on this system"), class = "Rcpp_stack_trace")), class = c("Rcpp::exception", 
"C++Error", "error", "condition"))) 
2.
workspace$get_default_datastore() 
1.
get_default_datastore(ws) 
```

**Additional context**
The specific platform I'm having an issue with is Windows 10 but I dare say the problem appears on on platforms behind a proxy presenting the self signed certificate.

**Comment by ashley-betts70** [comment]
I've now also tested with purely the python SDK. Same problem. I have used:

`$ conda config --set ssl_verify=False`
and confirmed it is writing to .condarc

This makes no difference.

Oddly some methods seem to work (i.e. create_workspace, load_workspace_from_config) but yet others fail (get_default_datastore, python - Experiment()).

**Comment by diondrapeck** [comment]
@ashley-betts70 - Yes, you're right. This issue has been confirmed to be on the Python SDK end. The reason you are experiencing it with some methods and not others is because not all methods directly call a client object. We will open a ticket internally and track this issue with it.

**Comment by ashley-betts70** [comment]
Hi @diondrapeck , thanks for raising the internal ticket. How will we know when the issue is resolved however?

Regards,

Ashley

**Comment by diondrapeck** [comment]
@ashley-betts70 We will keep this ticket open until it's resolved.
