### ISSUE TITLE
Error while trying to use get_workspace() from sdk

### ISSUE THREAD

**Issue by jay-aplan** [Azure/azureml-sdk-for-r#214]
Hi,
I have been trying to use the sdk for get the workspace as i want to be able to upload the dataset after R script execution. I have added. It keeps on giving me this error. I really want to use azureml sdk hence have been trying various things for sometime but if it goes like this i may give up on it.
 I have checked the logs and couldnt see anything useful. Let me know if any specific log i should look at for the issue.

ModuleExceptionMessage:FailedToEvaluateScript: The following error occurred during script evaluation, please view the output log for more information:
---------- Start of error message from R interpreter ----------
Got exception when invoking script: 'Failed to find execution status file /tmp/tmp74tu03kr/d06ac86b68cb49548f5dd7106936db9f.status'.
---------- End of error message from R  interpreter  ----------

My designer looks like:

![image](https://user-images.githubusercontent.com/32902481/71082122-7cb92a00-2188-11ea-9ef6-44a7fcf9cd12.png)

and the script inside it is

azureml_main <- function(dataframe1, dataframe2){
  if(!require(corrplot)) install.packages("corrplot", repos = "http://cran.us.r-project.org")
  if(!require(azuremlsdk)) install.packages("azuremlsdk", repos = "http://cran.us.r-project.org")
  library(corrplot)
  library(data.table)
  azuremlsdk::install_azureml()
  library(azuremlsdk)
  workspac <- get_workspace("workspacename", "subsid", "resourcename")
  return(list(dataset1=dataframe1, dataset2=dataframe2, dataset3=dataframe1))
}

**Comment by heemanshusuri** [comment]
It's hard to figure out the issue without further logs. In the script, could you call `library(azuremlsdk)` before `azuremlsdk::install_azureml()`? 

Could you verify if the R script is running fine in your local RStudio environment? This will help figure out where the issue is.
