### ISSUE TITLE
AttributeError: module 'azureml' has no attribute 'core'

### ISSUE THREAD

**Issue by Rens88** [Azure/azureml-sdk-for-r#217]
**Describe the bug**
I'm having issues with Azure Machine Learning SDK for R: "module 'azureml' has no attribute 'core'"...

I am trying to use azureml to apply machine learning (my own stuff, written in R) to data from our data warehouse that is put in the blob storage. The modelled output should be put back into the blob storage so it can be accessed from the data warehouse. I've written the code in R on my local machine (stored in a git repo). Preferably, I'd find some method to pull my code from git into a pipeline in the azureml environment so that it can be directly run whenever new data is available in the blob storage.

I've embarked on a tutorial-spree and found this seemingly relevant walkthrough: [Train and deploy your first model with Azure ML] (https://azure.github.io/azureml-sdk-for-r/#getting-started).

But... after trying all I could think of, I'm stuck on the first steps. After installing all (or at least.. that's what I think) packages, modules, apps etc, and running the following code in RStudio:

**To Reproduce**
`library(azuremlsdk)
    existing_ws <- get_workspace(name = name, 
                                 subscription_id = subscription_id, 
                                 resource_group)`

I run into an error that I haven't been able to fix:

> AttributeError: module 'azureml' has no attribute 'core'

**Expected behavior**
I expected to be able to load the workspace.

**Additional context**
It seems that the azuerml is supposed to have an attribute "core", but when looking at it more closely, there is indeed no such attribute. The function "get_workspace()" is trying to access: "azureml$core$Workspace$get". I found that "azuerML$Workspace" does exist, but then I can't figure out how to make that work.

Can anyone explain to me why I'm encountering this error? Does anyone know of a better tutorial on how to connect my R code the azureml's cloud service?

Any pointers in the right direction are much appreciated!

I also tried [stackoverflow](https://stackoverflow.com/questions/59683283/azure-machine-learning-integration-of-r-should-the-azureml-module-have-an-att?noredirect=1#comment105589285_59683283), but to no avail.

Apologies if this is not posted in the correct location, but I've been stuck at this for a while now. Any help towards a solution would be much appreciated.

**Comment by mx-iao** [comment]
Hi @Rens88,
Yes the GitHub issues for this repo is good place to report bugs, ask for help, etc. For StackOverflow, we monitor the tag [`azure-machine-learning-service`](https://stackoverflow.com/questions/tagged/azure-machine-learning-service) so if you tag your question with that we will be able to find and triage it quicker.

As for your issue, have you taken a look at our installation guide: https://azure.github.io/azureml-sdk-for-r/articles/installation.html. It has more details and information on common troubleshooting scenarios. Are you using R installed from CRAN?

**Comment by Rens88** [comment]
Hi @mx-iao,
Thanks for your response!
I updated my StackOverflow [post](https://stackoverflow.com/questions/59683283/azure-machine-learning-integration-of-r-should-the-azureml-module-have-an-att). It now also includes the right tag, so perhaps you've already seen it.
As I explain in that post (in much more detail), I followed all the available installation steps. I installed my R via CRAN.

It would be great if you could have a look at my post on StackOverflow.

**Comment by mx-iao** [comment]
Thanks! We will take a look at your StackOverflow post and follow up there.

**Comment by diondrapeck** [comment]
@Rens88 In deciding which Python environment to use for your project, _reticulate_ takes the first version with _numpy_ installed and uses it as the default, but in your case, this happens to not be where you've installed the SDK. In order to fix it, run `reticulate::py_discover_config()` which will list all Python versions found on your machine. Copy the full path of the one that ends in "\r-azureml\python.exe" and run `reticulate::use_python()` with the full path string inside the parenthesis.

Let me know if this works for you!

**Comment by Rens88** [comment]
Thanks for the suggestion @diondrapeck.
When I run `reticulate::py_discover_config()`, I get to see the following:

> reticulate::py_discover_config()
> python:         C:/.../AppData/Local/r-miniconda/envs/r-reticulate/python.exe
> libpython:      C:/.../AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
> pythonhome:     C:/.../AppData/Local/r-miniconda/envs/r-reticulate
> version:        3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)]
> Architecture:   64bit
> numpy:          C:/.../AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
> numpy_version:  1.17.4

This is not the python version with azuremlsdk installed. I know the path, so I just ran 'use_python' with that specific path:
`reticulate::use_python('C:/.../AppData/Local/r-miniconda/envs/r-azureml/python.exe')`

For the first time after restarting RStudio, if I run :
`library(azuremlsdk)`
`get_current_run()`

I get the following error:

> Error in py_get_attr_impl(x, name, silent) : 
>   AttributeError: module 'azureml' has no attribute '_base_sdk_common'
> In addition: Warning message:
> Python 'C:/.../AppData/Local/r-miniconda/envs/r-azureml/python.exe' was requested but 'C:/.../AppData/Local/r-miniconda/envs/r-reticulate/python.exe' was loaded instead (see reticulate::py_config() for more information) 

And when I run it for the second time, I get:

> Error in py_get_attr_impl(x, name, silent) : 
>   AttributeError: module 'azureml' has no attribute 'core'

As it seems there is some unwanted switching between Conda environments, I tried specifying the Conda enverionment with:
`reticulate::use_condaenv('r-azureml')` --> I also tried it with the full path.

For the first time after restarting RStudio, if I run :
`reticulate::use_condaenv('r-azureml')` 
`library(azuremlsdk)`
`get_current_run()`

I get the following error:

> Error in py_get_attr_impl(x, name, silent) : 
>   AttributeError: module 'azureml' has no attribute '_base_sdk_common'
> In addition: Warning message:
> could not honor request to load desired versions of Python; 'C:/.../AppData/Local/r-miniconda/envs/r-reticulate/python.exe' was loaded instead (see reticulate::py_config() for more information) 

And when I run it for the second time, I get the good old:

> Error in py_get_attr_impl(x, name, silent) : 
>   AttributeError: module 'azureml' has no attribute 'core'


Note that all "..." replacements in my posts refer to the same location. In other words, the subfolders containing my two conda environments ("r-azureml" and "re-reticulate") are in the same folder.
I also checked whether numpy is installed in my "r-azuerml" environment, it is:

> numpy==1.18.1


So the problem is still there.. Any other suggestions?

**Comment by Rens88** [comment]
I seemed to have fixed the issue by specifically installing the python package azureml AND azureml.core:

`python -m pip install azureml`
`python -m pip install azureml.core`

I did this for the Conda version that was called by R (r-reticulate). It's a bit odd to not be able to use the Conda environment 'r-azureml' without R switching back to 'r-reticulate', but ah well... at least I don't get my 'azureml' has no attribute 'core' anymore.

**Comment by diondrapeck** [comment]
@Rens88 - I'm glad you were able to get it working! I'll add your solution to our troubleshooting guide in case another user runs across it.

**Comment by mx-iao** [comment]
Hi @Rens88, turns out this issue was introduced because of the latest `reticulate` release 1.14. PR #221 addresses the issue and has been merged into master. This error should be resolved with a clean install of the SDK.

**Comment by hermandr** [comment]
Hi,

After updating to latest 1.10.0 version, I am getting this error and can't fix it.
I have installed in the r-reticulate folder
````
python -m pip install azureml
python -m pip install azureml.core
```
But it still compains with "has no attribute core"
