### ISSUE TITLE
Error submitting experiment: AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by revodavid** [Azure/azureml-sdk-for-r#225]
With current CRAN release (0.5.6) on Windows, attempting to submit an experiment gets this error when running through the vignette `train-and-deploy-to-aci.Rmd`.

```r
> run <- submit_experiment(exp, est)
WARNING - 'gpu_support' is no longer necessary; AzureML now automatically detects and uses nvidia docker extension when it is available. It will be removed in a future release.
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'NoneType' object has no attribute 'lower'
```

**To Reproduce**
Install azuremlsdk from CRAN (v 0.5.6) and attempt to run the vignette `train-and-deploy-to-aci.Rmd`.

**Additional context**
This error goes away with version 0.5.7.9000, but providing this issue for the benefit of CRAN users who may experience the error.

**Comment by mx-iao** [comment]
Closing as issue has been resolved.
