### ISSUE TITLE
Azure Data Lake Gen 2 datastore connection from R

### ISSUE THREAD

**Issue by edocastro** [Azure/azureml-sdk-for-r#230]
We currently have customers that have a lot of code written in R and we are migrating them to Azure. How can we connect from R to Azure Data Lake Gen 2 Datastore?

**Comment by mx-iao** [comment]
Hi @edocastro ,
We can add a new method for the SDK for registering a Azure Data Lake Gen 2 datastore:
`register_azure_data_lake_gen2_datastore(workspace, datastore_name, filesystem, account_name, tenant_id, client_id, client_secret, resource_url = NULL, authority_url = NULL, protocol = NULL, endpoint = NULL, overwrite = False)`

You will then be able to interact with this type of datastore with the existing datastore methods.

Does this address your scenario? If so we can add this to the SDK.

**Comment by edocastro** [comment]
Yes it will address my scenario. Thanks

**Comment by mx-iao** [comment]
Sounds good, we'll get started on this

**Comment by mx-iao** [comment]
Method has been added with #279
