### ISSUE TITLE
azureml.get_model_path dont search in  azureml-models

### ISSUE THREAD

**Issue by JLSMforPYR** [Azure/azureml-sdk-for-r#234]
I'm trying to load a model from azureml that I've registred previouly. I have checked that the model is save, but when I use azureml$get_model_path("model_name") return an error  Model not found in cache or in root. Why this function dont search in azureml-models?

**Comment by diondrapeck** [comment]
Hi @JLSMforPYR - do you have multiple versions of this model saved to your workspace? If so, you may need to specify the version, e.g. `my_model <- azureml$get_model_path(model_name='my_model_name', version='my_model_version')`

**Comment by JLSMforPYR** [comment]
No, I dont have multple versions of the model.

**Comment by diondrapeck** [comment]
Have you tried adding DEBUG logging to get more information about the issue? If not, [here's an example from our docs](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-troubleshoot-deployment#function-fails-get_model_path). Let me know if this helps.
