### ISSUE TITLE
grid_parameter_sampling with choice errors with fixed values

### ISSUE THREAD

**Issue by ashley-betts70** [Azure/azureml-sdk-for-r#238]
Hi,
    I'm trying to get a hyperparameter example working using grid_parameter_sampling. When using vectors to supply discrete values such as "nrounds" = choice(c(100,200)) this works fine. If however I wish to fix a parameter I am unable to. For example "gamma"= choice(c(0)) returns error:

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'float' object is not iterable 

As does  "gamma"= choice(0).   "gamma"= 0 returns:

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'float' object is not subscriptable 

The documentation for choice states that it will accept either an integer vector or one or more comma separated discrete values. The first condition seems to be true but if you supply multiple discreet values separated by commas the following error is returned:

Error in choice(1, 2) : unused argument (2)

I'm guessing the last case is due to R documentation being aligned to the python doco.

For the grid_parameter_sampling function to be useful it needs to be able to fix parameters and allow a list of discrete values of types other than integer (i.e. float, char)

Regards,

Ashley

**Comment by diondrapeck** [comment]
Hi @ashley-betts70, thanks for making us aware of this. This seems to be the product of poor documentation. The `choice` function actually will only accept a vector of values; "loose" values will raise an error as you found. I apologize for the incorrect documentation and subsequent confusion. We'll make it a priority to fix that function documentation and clarify examples.

As for fixing a parameter, best practice is to assign it as a script parameter when making your estimator and exclude it from your list of hyperparameters:

```r
# set all script params for estimator
script_params <- list(batch_size = 32, epochs = 200, lr = 0.0001, decay = 1e-6)
est <- estimator(source_directory = ".", entry_script = "cifar10_cnn.R",
compute_target = compute_target, script_params = script_params)

# exclude batch_size param from sampling if we don't want it changed
sampling <- random_parameter_sampling(list(epochs = choice(c(200, 350, 500)),
                                           lr = normal(0.0001, 0.005),
                                           decay = uniform(1e-6, 3e-6)))

hyperdrive_config <- hyperdrive_config(sampling, "Loss", primary_metric_goal("MINIMIZE"),
                                       4, policy = bandit_policy(slack_factor = 0.15), estimator = est)
```

Let us know if you have any more questions. I'll close this issue once the documentation has been improved.

**Comment by ashley-betts70** [comment]
No worries, thanks @diondrapeck.
