### ISSUE TITLE
Add function to register model to run

### ISSUE THREAD

**Issue by diondrapeck** [Azure/azureml-sdk-for-r#244]
**Is your feature request related to a problem? Please describe.**
There isn't a wrapped function to allow registering a model with a run - only for registering a model to a workspace. Both are possible in Python SDK, and we should have parity. This is a user request.

**Describe the solution you'd like**
Add `register_model_to_run` function

**Comment by mx-iao** [comment]
I think it should be `register_model_from_run()` since the most likely scenario is that the user is registering the model from inside a run in their training script. Lmk what you think

**Comment by nswitanek** [comment]
`register_model_from_run()` is sensible and would be helpful, but probably called not from inside a run inside a training script, but from outside the train.R script after comparison between model runs produced across multiple runs (instantiations/parameterizations) of train.R scripts.

**Comment by mx-iao** [comment]
good point, either scenario should work: 1) register from inside training script or 2) register from the control plane (not inside train.R).

here is the function signature we should have for the model:
```r
register_model_from_run <- function(run, model_name, model_path = NULL, tags = NULL, properties = NULL, description = NULL, datasets = NULL, sample_input_dataset = NULL, sample_output_dataset = NULL)
```

@diondrapeck we should also expose the `sample_input_dataset` and `sample_output_dataset` parameters to the existing [register_model()](https://azure.github.io/azureml-sdk-for-r/reference/register_model.html) method
