### ISSUE TITLE
vignettes not discoverable

### ISSUE THREAD

**Issue by revodavid** [Azure/azureml-sdk-for-r#248]
**Describe the bug**
Most vignettes are not listed at https://cran.r-project.org/package=azuremlsdk ;  only the `installation` and `configuration` vignettes are shown. Same goes for `vignette(package="azuremlsdk")` and the "vignettes" link shown by `help(package="azuremlsdk")`

**To Reproduce**
```
vignette(package="azuremlsdk")
```

**Expected behavior**
All vignettes are listed.

**Screenshots**
On CRAN:
![image](https://user-images.githubusercontent.com/152948/74597262-25620800-50ac-11ea-95c7-51c5e61a3307.png)

In Help window after `help(package="azuremlsdk")`:
![image](https://user-images.githubusercontent.com/152948/74597278-74a83880-50ac-11ea-99ee-239d2271fbf7.png)

**Additional context**
I think this is due to most vignettes being provded in subfolders of the `vignettes` folder.

**Comment by mx-iao** [comment]
Yes this is due to the other vignettes being in subfolders for clarity, since many of them have additional dependency files. Until we find a better solution this is unfortunately the case.

**Comment by revodavid** [comment]
Request reopen @diondrapeck . The bit is going rogue.

**Comment by revodavid** [comment]
@mx-iao The problem is that R users have literally no way of reading these vignettes right now. I think one solution is to move the .Rmd files to the top-level `vignettes` folder, and use subfolders and relative file names for the data files. You can also put data and ancillary files in the `inst` folder of the package.

**Comment by revodavid** [comment]
Addressed by #320

**Comment by mx-iao** [comment]
Closing now that #320 has been merged.
