### ISSUE TITLE
view_run_details function does not work in RStudio Server on Compute Instance

### ISSUE THREAD

**Issue by sdonohoo** [Azure/azureml-sdk-for-r#249]
**Describe the bug**
view_run_details() widget does not work within RStudio Server session on new Compute Instances which it does work in RStudio Server on Notebook VMs. The view_run_details code incorrectly extracts the instance name and domain_suffix from "~/../../mnt/azmnt/.nbvm" so defaults to localhost as the widget endpoint in the viewer/browser. On both NBVM and CI, the file exists and is in the same location but on NBVM, the file contains a blank line at line 1. Instance_name and domain_suffix are read from lines 2 and 3. On CI, the blank line is no longer there so instance name and domain_suffix are read incorrectly.

**To Reproduce**
1. Create an instance of Compute Instance in a region where CI is available
2. From RStudio Server on the CI, run the train local sample for the R SDK.
3. RStudio Viewer tries to open run status widget at localhost and is unable to dsplay.

**Expected behavior**
Viewer display run details widget:
![image](https://user-images.githubusercontent.com/1457586/74615409-1009cf80-50e6-11ea-8f6e-1720f23826e5.png)

**Screenshots**
In Jobs tab: [1] "Listening on 127.0.0.1:7580".
In RStudio Viewer when failing: ![image](https://user-images.githubusercontent.com/1457586/74615317-35e2a480-50e5-11ea-9cc7-cbd21be27417.png)

**Additional context**
Fix: if length(nvbm) after the readLines == 3, the file is on a NVBM -> read lines 2 and 3. If length(nvbm) == 2 ,the file is on a CI -> read lines 1 and 2.
Temp workaround on CI: edit "~/../../mnt/azmnt/.nbvm" to add blank line at top of file.

**Comment by mx-iao** [comment]
Thanks Scott! You are correct that issue is due to the changes from NBVM to CI. We are aware of the issue and @diondrapeck is currently implementing the fix.
