### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) :    AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by MadNietzsche** [Azure/azureml-sdk-for-r#250]
While going through the tutorial on "train-and-deploy-on-aci.Rmd" in the Azure ML examples, I came across this issue while running the "create_inference_config" chunk:

```r
> inference_config <- inference_config(entry_script = "accident_predict.R",
                                       source_directory = ".",
                                       environment = r_env)

## Error in py_call_impl(callable, dots$args, dots$keywords) : 
## AttributeError: 'NoneType' object has no attribute 'startswith'
```

I think that this has to do with some version of component in the python back-end but I'm not sure as I cannot find the source code for this.

Could you please enlighten me on the solution? Below you can find the R session details for the RStudio session inside the Azure ML platform.

```r
## R version 3.6.2 (2019-12-12)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 16.04.6 LTS

## Matrix products: default
## BLAS:   /usr/lib/libblas/libblas.so.3.6.0
## LAPACK: /home/azureuser/.local/share/r-miniconda/envs/r-reticulate/lib/libmkl_rt.so

## locale:
## [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8    
## [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8 LC_NAME=C                 
## [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     

## other attached packages:
## [1] azuremlsdk_0.5.7

## loaded via a namespace (and not attached):
## [1] htmlwidgets_1.5.1 compiler_3.6.2    tools_3.6.2       htmltools_0.4.0   rappdirs_0.3.1 reticulate_1.14  
## [7] Rcpp_1.0.3        knitr_1.26        jsonlite_1.6      xfun_0.11         digest_0.6.23     rlang_0.4.2 
```

**Comment by mx-iao** [comment]
Can you update to azuremlsdk v 0.6.85 from [CRAN](https://cran.r-project.org/web/packages/azuremlsdk/index.html) and then run `azuremlsdk::install_azureml(envname = 'r-reticulate')`

**Comment by diondrapeck** [comment]
@MadNietzsche - I'll keep this issue open while we investigate, but in the meantime, I wasn't able to reproduce your issue with the latest version from CRAN, so upgrading your package should fix that.

**Comment by diondrapeck** [comment]
@MadNietzsche - I just tested that example on a Notebook VM with version 0.5.7, and I still was unable to reproduce. Could you post more details of the error (if any) and the full script you ran (minus account information)?

**Comment by MadNietzsche** [comment]
Thank you, both. The issue was fixed by upgrading azuremlsdk
