### ISSUE TITLE
Missing documentation: How to create a dataframe from an Azure SQL Database already registered into the Datastore

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#256]
I'm trying to create a dataframe from an Azure SQL DB registered into the Datastore.
I'm trying to do that using TabularDatasets with this command:

`azureml$core$dataset$Dataset$Tabular$from_sql_query(sqlQuery)`

but I'm getting a mysterious issue:

> " Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   TypeError: Invalid argument value or type. Please refer to the documentation for accepted types."

It'd be great to have a companion documentation helping us to do basic operations with the R SDK. For example, just adding the "R" tab to the code chunks in pages like the following one could be the way to go:

[Create Azure Machine Learning datasets](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets)

**Comment by mx-iao** [comment]
Hi @lucazav thanks for the feedback. We are in the process of adding datasets documentation. What is the value of `sqlQuery` you are feeding into the call?

**Comment by lucazav** [comment]
Hi @mx-iao , it's something like this:

```
SELECT
	...
FROM MySchema.MyTable AS AU
WHERE
	DATEDIFF(DAY, AU.ReferenceDate, GETDATE()) >= 90

```
I've already tested it using Azure Data Studio pointing directly to my Azure SQL Database.
I've also registered my Azure SQL Database to the Datastore

**Comment by mx-iao** [comment]
The [`query` parameter](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.dataset_factory.tabulardatasetfactory?view=azure-ml-py#from-sql-query-query--validate-true--set-column-types-none-) of `from_sql_query()` takes in (datastore, query).

Until we have the docs in R, here's the example in Python from the [docs](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets):
```
from azureml.core import Dataset, Datastore

# create tabular dataset from a SQL database in datastore
sql_datastore = Datastore.get(workspace, 'mssql')
sql_ds = Dataset.Tabular.from_sql_query((sql_datastore, 'SELECT * FROM my_table'))
```
Since you are using reticulate right now and the query parameter requires a tuple of (datastore, query), I think you will have to do something like `query = tuple(datastore, query)`.

This is very useful feedback for us actually - I think for the R method it will make more sense to split the datastore and query into two separate parameters. @diondrapeck FYI

**Comment by lucazav** [comment]
So should I use this R code:

`azureml$core$dataset$Dataset$Tabular$from_sql_query( list(sql_ds, sqlQuery) )`

or the _query_ parameter needs specific names (_name1_ and _name2_) for its elements, like:

`azureml$core$dataset$Dataset$Tabular$from_sql_query( list(name1 = sql_ds, name2 = sqlQuery) )`

?

**Comment by mx-iao** [comment]
the query parameter in the Python SDK expects a tuple. so I believe you will need:
`azureml$core$dataset$Dataset$Tabular$from_sql_query(tuple(sql_ds, sqlQuery))`

**Comment by mx-iao** [comment]
@diondrapeck I just confirmed with the datasets team that you can also do `DataPath(datastore, 'SELECT * FROM my_table')` for SQL datastores. So once we add the corresponding `data_path()` method in R SDK from #247 this will address the scenario for `create_tabular_dataset_from_sql_query()`

**Comment by lucazav** [comment]
I executed this code:

`tdf <- azureml$core$dataset$Dataset$Tabular$from_sql_query(reticulate::tuple(sql_ds, sqlQuery))`

and I'm getting this error:

>  Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   DatasetValidationError: Cannot load any data from the datastore using the SQL query "{}". Please make sure the datastore and query is correct. 

I've double-checked both the variables _sql_ds_ and _sqlQuery_ are correct.

**Comment by mx-iao** [comment]
This appears to be an underlying datasets service issue. We are investigating with the team right now.

**Comment by lucazav** [comment]
Could you give me a workaround to load data from Azure SQL Database, please?
Thank you.

**Comment by mx-iao** [comment]
@MayMSFT can you please provide a workaround?

**Comment by diondrapeck** [comment]
@lucazav  - the `data_path` function has been added.

**Comment by sachinparyani** [comment]
Hi @lucazav,

I'm an engineer from the AML Dataset team and I can help take a look at this issue. Do you mind telling me what the exact SQL query is that you are running? The reason I ask is because we have had issues with SQL queries that use COUNT, AVG and the likes. If you have something like SELECT COUNT(column_name) FROM $$$ , one workaround is to replace it with SELECT COUNT(column_name) **AS count_alias** FROM $$$.

**Comment by lucazav** [comment]
Hi @sachinparyani ,

I tried with a simple `SELECT TOP 100 * FROM my_schema.my_table`.

**Comment by lucazav** [comment]
Hi @mx-iao ,

supposing the query works fine (I'm still waiting to fix it), I'll have the `tdf` tabular dataset. How can I get an R data frame from `tdf`? Is `as.data.frame` enough?

**Comment by mx-iao** [comment]
@sachinparyani do you have a list of known issues/troubleshooting for these sorts of datasets issue? That way we can link to those from our documentation.

**Comment by sachinparyani** [comment]
Hi @lucazav ,

Thank you letting me know what the query is. Since we do not know what the underlying error is. I would like you try the following:

1. Please update your azureml-core (https://pypi.org/project/azureml-core/1.1.2rc0/) and azureml-dataprep (https://pypi.org/project/azureml-dataprep/1.3.0/) python packages to the latest and try.  We recently made some changes to our error handling mechanism. This will allow us see the right error messages at the very least.
2. Please try with the same with a simple sql query like SELECT * FROM TABLE_NAME if you have not already. This will help us in narrowing down the issue.
3. Please also try by explicitly setting the validate option to true. You can do so by proving an extra argument _validate_ to the from_sql_query() method.

Please keep me updated once you've done some/all of these steps. Thank you!

**Comment by sachinparyani** [comment]
@mx-iao Don't think there is a list per se that I am aware of. However, if I do happen to compile one, I will make sure to update you.

**Comment by lucazav** [comment]
Hi @sachinparyani,

how can I update those packages from RStudio? Have I to manually install them into the environment created by the `azuremlsdk` library?

**Comment by lucazav** [comment]
I tried with this code:

```
remotes::install_github('https://github.com/Azure/azureml-sdk-for-r')

azuremlsdk::install_azureml(version = "1.1.2rc0", remove_existing_env = TRUE)
```

but I'm getting the following error:

> # All requested packages already installed.
> 
> Collecting azureml-sdk==1.1.2rc0
>   Using cached azureml_sdk-1.1.2rc0-py3-none-any.whl (4.6 kB)
> Collecting numpy
>   Using cached numpy-1.18.1-cp36-cp36m-win_amd64.whl (12.8 MB)
> Collecting pandas
>   Using cached pandas-1.0.1-cp36-cp36m-win_amd64.whl (8.8 MB)
> ERROR: Could not find a version that satisfies the requirement azureml-core==1.1.2.* (from azureml-sdk==1.1.2rc0) (from versions: 0.1.50, 0.1.57, 0.1.58, 0.1.59, 0.1.65, 0.1.68, 0.1.74, 0.1.80, 1.0rc83, 1.0rc85, 1.0.2, 1.0.6, 1.0.8, 1.0.10, 1.0.15, 1.0.17, 1.0.17.1, 1.0.18, 1.0.21, 1.0.23, 1.0.30, 1.0.33, 1.0.33.1, 1.0.39, 1.0.41, 1.0.41.1, 1.0.43, 1.0.43.1, 1.0.45, 1.0.48, 1.0.53, 1.0.55, 1.0.57, 1.0.57.1, 1.0.60, 1.0.62, 1.0.65, 1.0.65.1, 1.0.69, 1.0.72, 1.0.74, 1.0.76, 1.0.79, 1.0.81, 1.0.81.1, 1.0.83, 1.0.85, 1.0.85.1, 1.0.85.2, 1.0.85.3, 1.0.85.4, 1.0.85.5, 1.1.0rc0, 1.1.1rc0, 1.1.1.1rc0, 1.1.1.2rc0, 1.1.2rc0)
> ERROR: No matching distribution found for azureml-core==1.1.2.* (from azureml-sdk==1.1.2rc0)
> Error: Error installing package(s): "azureml-sdk==1.1.2rc0", "numpy", "pandas"

Any help, please?

**Comment by lucazav** [comment]
Hi @sachinparyani ,

I found a way to install the packages you suggested via reticulate.
First of all, I installed the last stable version of SDK:

`azuremlsdk::install_azureml(version = "1.0.85", remove_existing_env = TRUE)`

Then I run the following code:

```
library(reticulate)

py_install("azureml-core==1.1.2rc0", envname = "r-reticulate", pip = TRUE)
py_install("azureml-dataprep==1.3.0", envname = "r-reticulate", pip = TRUE)
```

After that, I registered a new Azure SQL Database Datastore entry using the UI. 
So I tried to connect to my azure sql db in the following way:

```
sql_ds <- get_datastore(ws, "my_azuresqldb")
sqlQuery <- "SELECT * FROM my_schema.my_table"

dp <- data_path( sql_ds, sqlQuery )
create_tabular_dataset_from_sql_query(dp)
```

and I get this error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   DatasetValidationError: Cannot load any data from the datastore using the SQL query "<azureml.data.datapath.DataPath object at 0x000001ABEFCFB278>". Please make sure the datastore and query is correct.
> Could not connect to specified database.|session_id=xxx

As a double-check I tried to get the data using directly the Python SDK and all works fine:

![image](https://user-images.githubusercontent.com/6104437/75983685-410d4100-5ee9-11ea-8f2b-2b15e6d85054.png)

So there is a problem with the R SDK.

**Comment by sachinparyani** [comment]
A reason I can think of is that your compute instance environment may have different packages installed. Is there a way for you to check the contents of 'pip list' on both environments? The important packages to consider are azure, azureml-core, azureml-sdk and azureml-dataprep. Also, is your on-prem RStudio behind a VNet or a firewall? I'm not completely familiar with how environments work in R but is there a difference between environments and packages installed in your Python SDK setup vs your R SDK setup?

**Comment by sachinparyani** [comment]
@lucazav  Did you get a chance to look into the differences?

**Comment by lucazav** [comment]
Hi @sachinparyani, sorry for my delay.
Here the packages on my on-premises installation:

> Package                              Version
> ------------------------------------ -------------------
>...
> azure-common                         1.1.25
> azure-graphrbac                      0.61.1
> azure-mgmt-authorization             0.60.0
> azure-mgmt-containerregistry         2.8.0
> azure-mgmt-keyvault                  2.1.1
> azure-mgmt-resource                  8.0.1
> azure-mgmt-storage                   8.0.0
> azureml-automl-core                  1.0.85.5
> azureml-core                         1.0.85.5
> azureml-dataprep                     1.1.38
> azureml-dataprep-native              13.2.0
> azureml-pipeline                     1.0.85
> azureml-pipeline-core                1.0.85.1
> azureml-pipeline-steps               1.0.85
> azureml-sdk                          1.0.85
> azureml-telemetry                    1.0.85.2
> azureml-train                        1.0.85
> azureml-train-automl-client          1.0.85.4
> azureml-train-core                   1.0.85
> azureml-train-restclients-hyperdrive 1.0.85
> ...

Here the packages list of my compute instance:

> 
> Package                               Version
> ------------------------------------- -------------
>...
> azure-common                          1.1.24
> azure-graphrbac                       0.61.1
> azure-mgmt-authorization              0.60.0
> azure-mgmt-containerregistry          2.8.0
> azure-mgmt-keyvault                   2.0.0
> azure-mgmt-resource                   7.0.0
> azure-mgmt-storage                    7.0.0
> azure-storage-blob                    2.1.0
> azure-storage-common                  2.1.0
> azureml-automl-core                   1.0.83.1
> azureml-automl-runtime                1.0.83
> azureml-contrib-datadrift             1.0.83
> azureml-contrib-interpret             1.0.83
> azureml-contrib-notebook              1.0.83
> azureml-contrib-pipeline-steps        1.0.83
> azureml-contrib-reinforcementlearning 1.0.83
> azureml-contrib-server                1.0.83
> azureml-contrib-services              1.0.83
> azureml-core                          1.0.83
> azureml-datadrift                     1.0.83
> azureml-dataprep                      1.1.35
> azureml-dataprep-native               13.2.0
> azureml-defaults                      1.0.83
> azureml-explain-model                 1.0.83
> azureml-interpret                     1.0.83
> azureml-mlflow                        1.0.83
> azureml-model-management-sdk          1.0.1b6.post1
> azureml-opendatasets                  1.0.83
> azureml-pipeline                      1.0.83
> azureml-pipeline-core                 1.0.83
> azureml-pipeline-steps                1.0.83
> azureml-samples                       0+unknown
> azureml-sdk                           1.0.83
> azureml-telemetry                     1.0.83
> azureml-tensorboard                   1.0.83
> azureml-train                         1.0.83
> azureml-train-automl                  1.0.83
> azureml-train-automl-client           1.0.83
> azureml-train-automl-runtime          1.0.83.1
> azureml-train-core                    1.0.83
> azureml-train-restclients-hyperdrive  1.0.83
> azureml-widgets                       1.0.83

**Comment by sachinparyani** [comment]
@lucazav Thank you sharing the lists! I see that you're azureml-dataprep version in the on-prem case is slightly older. Do you mind updating it to the latest version, which is 1.3.5 (https://pypi.org/project/azureml-dataprep/1.3.5/). While you're at it, if you could also update azureml-core to the latest version, which is 1.1.5.3 (https://pypi.org/project/azureml-core/1.1.5.3/), that would be great. Once you're done updating, please try again and let me know if you're still unable to run the query. Thank you!

**Comment by lucazav** [comment]
Hi @sachinparyani ,
I've updated the packages you mentioned in the following way from my on-prem RStudio:

```
reticulate::py_install("azureml-core==1.1.5.3", envname = "r-reticulate", pip = TRUE)
reticulate::py_install("azureml-dataprep==1.3.5", envname = "r-reticulate", pip = TRUE)
```
During the installation of `azureml-dataprep` I got these error messages:

> ERROR: azureml-train-automl-client 1.0.85.4 has requirement azureml-core==1.0.85.*, but you'll have azureml-core 1.1.5.3 which is incompatible.
> ERROR: azureml-train-automl-client 1.0.85.4 has requirement azureml-dataprep<1.2.0a,>=1.1.37a, but you'll have azureml-dataprep 1.3.5 which is incompatible.
> ERROR: azureml-sdk 1.0.85 has requirement azureml-core==1.0.85.*, but you'll have azureml-core 1.1.5.3 which is incompatible.
> ERROR: azureml-sdk 1.0.85 has requirement azureml-dataprep[fuse]<1.2.0a,>=1.1.37a, but you'll have azureml-dataprep 1.3.5 which is incompatible.
> ERROR: azureml-automl-core 1.0.85.5 has requirement azureml-dataprep<1.2.0a,>=1.1.37a, but you'll have azureml-dataprep 1.3.5 which is incompatible.

Anyway the installation returns a successful message.

Then I run the following code:

```
sql_ds <- get_datastore(ws, "my_azuresqldb")

dp <- data_path( sql_ds, sqlQuery )

tds <- create_tabular_dataset_from_sql_query(dp)
```

but I got the following error:

>  Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   DatasetValidationError: Cannot load any data from the datastore using the SQL query "{}". Please make sure the datastore and query is correct.

> 3 stop(structure(list(message = "DatasetValidationError: Cannot load any data from the datastore using the SQL query \"{}\". Please make sure the datastore and query is correct.",      call = py_call_impl(callable, dots$args, dots$keywords),      cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available on this system"), class = "Rcpp_stack_trace")), class = c("Rcpp::exception",  "C++Error", "error", "condition")))
> 
> 2 azureml$core$dataset$Dataset$Tabular$from_sql_query(query, validate,      set_column_types)
> 
> 1 create_tabular_dataset_from_sql_query(dp)

**Comment by sachinparyani** [comment]
@lucazav  Thank you for providing this information! I will check with our R team and get back to you.

**Comment by sachinparyani** [comment]
@mx-iao from the R team to provide and update.

**Comment by diondrapeck** [comment]
@lucazav - could you try using the new `query_timeout` param with `create_tabular_dataset_from_query`? The default is 30 seconds, so try increasing it from that. This would hopefully mitigate the 408 issue you came across.

**Comment by mx-iao** [comment]
@lucazav what version of azureml-dataprep do you have on your local machine? You can find this by running
```
conda activate r-reticulate
pip list
```
and finding azureml-dataprep

**Comment by mx-iao** [comment]
@lucazav we have traced the above error `Error in py_call_impl(callable, dots$args, dots$keywords) :
OSError: [WinError 6] The handle is invalid` to an issue on Windows in the newer updates to azureml-dataprep which @sachinparyani is patching. As a workaround if you downgrade your `azureml-dataprep` version to 1.3.0 that should mitigate the error you are seeing,

**Comment by lucazav** [comment]
Thank you @mx-iao

**Comment by sachinparyani** [comment]
@lucazav, we've fixed the bug and you should be able to verify it with the latest version of azureml-dataprep (1.4.6). Please let us know if you're still facing the issue. If that's the case the issue can be reopened.

**Comment by mx-iao** [comment]
@lucazav you can either upgrade the azureml-dataprep with `pip install --upgrade azureml-dataprep` or do a clean install of the python SDK with `azuremlsdk::install_azureml()` with `remove_existing_env = True`. Thanks @sachinparyani for the fix!

**Comment by lucazav** [comment]
Thank you all, guys!
