### ISSUE TITLE
Missing timezone data and Olson database

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#260]
My run went in error with this message into the _70_driver_log.txt_ file:

> Error: Unknown TZ UTC
> In addition: Warning message:
> In OlsonNames() : no Olson database found
> Execution halted

I suppose I'm facing into the same issue I found here:

[R missing timezone data and Olson database](https://github.com/jupyter/docker-stacks/issues/502)

I added the locale to the _read_csv_ call, but it seems not working.
Maybe adding `tzdata` to the R pre-requisites for docker containers will solve the warning.

**Comment by diondrapeck** [comment]
Hi @lucazav - thanks for bringing it to our attention. I'll close this issue once the images have been updated. In the meantime, you could try passing in your own docker image with the tzdata package installed using the custom_docker_image param in estimator().

**Comment by diondrapeck** [comment]
@lucazav - What exactly are you trying to do when you get this error? Is it a routine run? Inferencing? Is the timezone information particularly relevant to the script you're using?

**Comment by lucazav** [comment]
Hi @diondrapeck, 

I'm using the `readr::read_csv` function.

Is it enough to pass just the param in this way:

```
est <- estimator(source_directory = ".",
                 entry_script = "training_clustering.R",
                 cran_packages = c("tidyverse", "dtwclust", "clue"),
                 custom_docker_image = c("tzdata"),
                 script_params = list("--data_folder" = ds$path(target_path)),
                 compute_target = compute_target
```
?

**Comment by lucazav** [comment]
Hi @diondrapeck ,

I don't know how to build the right docker image having all the required dependencies.
Could you help me?

May be it would have been more convenient to have a parameter that allows you to simply pass a custom Python package as dependency to install to the default docker container built by AzureML, such as:

```
est <- estimator(source_directory = ".",
                 entry_script = "training_clustering.R",
                 cran_packages = c("tidyverse", "dtwclust", "clue"),

                 custom_docker_dependency_packages = c("tzdata"),

                 script_params = list("--data_folder" = ds$path(target_path)),
                 compute_target = compute_target )
```

**Comment by diondrapeck** [comment]
So, the `custom_docker_image parameter` should be the name of the Dockerfile you want to use - not the packages you'd want added to a Dockerfile. See the [documentation](https://azure.github.io/azureml-sdk-for-r/reference/estimator.html) for the `estimator` function.

A good Dockerfile example to start with is [the one we provide in our GitHub repo](https://github.com/Azure/azureml-sdk-for-r/blob/master/.azure-pipelines/docker/Dockerfile). For the tzdata addition, you could try adding it to lines 18-19 where the other Python packages are installed. Then, save that Dockerfile in your project folder and pass its path as a string into `estimator` using the `custom_docker_image` param. 

We don't currently have plans to allow users to specify Python packages as well as R packages when creating a run because it would make image building much more of a hassle and limit our ability to debug and ensure that packages aren't conflicting and causing image build failures. That's why it's left up to the user to create their own Docker image for those more detailed cases. After all, while they are connected, the R SDK is meant to be thought of as an implementation of the Python SDK in the R language, not a hybrid of both languages. 

Please let me know if you have more questions.

**Comment by lucazav** [comment]
Is it a problem for you to provide such a modified Dockerfile in a public repository in the meantime you'll solve the issue?
Thank you so much.

**Comment by lucazav** [comment]
Hi @mx-iao ,

I'm asking for the modified Dockerfile because I don't have an Ubuntu environment to generate it. If you could provide it, I'll continue to test my training run.

Thank you.

**Comment by mx-iao** [comment]
Hi @lucazav,
A clarification - `custom_docker_image` takes in the name of the Docker image, not the Dockerfile. The compute instance should have Docker installed if you are able to use it as an alternative environment to modify the Dockerfile and build the image.

Btw, we are currently working on a bit of refactoring of our r_environment/estimator to make the environment definition process easier and more transparent. We are also planning on publishing a curated environment(s).

**Comment by lucazav** [comment]
Hi @mx-iao ,

thank you for your info.
Could you tell me more or less when the package `tzdata` will be added to the pre-requisites for docker containers? Thanks

**Comment by lucazav** [comment]
Hi @mx-iao ,

any news on the adding of the `tzdata` package dependence?

**Comment by mx-iao** [comment]
Hi @lucazav,
We generally try to avoid adding additional packages to the default image for R to keep the size down. You can create a custom_docker_image that includes this package. @heemanshusuri if there's anything you can add here.

**Comment by lucazav** [comment]
It’s really important to add the `tzdata` dependence, otherwise you’ll always have errors when dealing with date/time in readr.
Take a look here: https://github.com/tidyverse/readr/issues/952#issuecomment-451255375

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mx-iao** [comment]
I see. We'll take a look at adding this then as part of some additional work we are doing right now for the default images.  It should land some time this month but I can't give a more exact ETA yet.

**Comment by heemanshusuri** [comment]
Hi @lucazav,

Unfortunately, we won't be able to add this package in the base image as of now. Please create a custom docker image and you can pass it to the `estimator` function.

**Comment by lucazav** [comment]
I managed to create a custom docker image and I pushed it on Docker Hub:
[R SDK Custom Docker Image](https://hub.docker.com/repository/docker/lucazav/r-sdk-docker-img)

Could you confirm that anyone who will use:

`custom_docker_image = "lucazav/r-sdk-docker-img:v1"`

in their `estimator` definition, automatically will get the image from Docker Hub?

Thank you.

**Comment by lucazav** [comment]
Hi @mx-iao ,
I've updated my Docker image in the Hub. But if I exec a run using that image, it seems Azure ML uses the previous cached image (I can't see the "20_*" log file.
Is there a way to force to delete the cached image?

**Comment by mx-iao** [comment]
For the warning you are getting, have you tried updating the version of the Python SDK used in the remote run to 1.1.5.1? That may get rid of the issue. If your image on Docker Hub is public then anyone should be able to use it - let me try a run with your image to verify.

Azure ML uses a hash of the environment specifications to determine if it should rebuild or use the previously cached image. If you've made changes to your docker image, you can try publishing that with a new tag. @heemanshusuri @diondrapeck for any additional best practices for invalidating the cache and triggering a new rebuild.

**Comment by lucazav** [comment]
I've just added the command to update the Python SDK into the Dockerfile. I'm compiling the new image and then I'll push it with a new tag (v2). Thanks!

**Comment by lucazav** [comment]
No way. I used the image V2 in my estimator, but Azure ML didn't compiled a new image.
Any help?

**Comment by mx-iao** [comment]
Hm, let me look into that. Meanwhile if you specify some arbitrary new package to cran_packages (which you don't have to actually use btw) that should invalidate the cache.

**Comment by mx-iao** [comment]
@lucazav, just followed up with the team - currently Azure ML detects Docker image changes via digest, so changing a tag without changing the underlying image won't make a difference (and won't trigger a rebuild). Let me know if you're seeing issues with this still.

**Comment by lucazav** [comment]
I've added a CRAN package as you suggested and the new image was built and worked like a charm!

**Comment by mx-iao** [comment]
Great! In general, changing an image should trigger a rebuild so let us know if this doesn't seem to be the case for you at any point.
