### ISSUE TITLE
Enrich documentation: Add tenant auth to "Set up an Azure ML Workspace"

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#261]
Since I have multiple workspaces in different tenants, I had to run this command to login interactively to the wanted tenant:

`azuremlsdk::azureml$core$authentication$InteractiveLoginAuthentication(tenant_id = '<my-tenant-id>')`

I think it'd better to add this code to the main vignettes and their related official documentation, like this one:

[Set up an Azure ML workspace](https://azure.github.io/azureml-sdk-for-r/articles/configuration.html)

 I lost a couple of hours trying to understand how to solve the error:

> You are currently logged-in to XXX tenant. You don't have access to subscription..."

**Comment by diondrapeck** [comment]
Thanks, @lucazav. This is a good idea. We'll close this issue once the documentation is updated.

**Comment by mx-iao** [comment]
@diondrapeck I think we can add this [method](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.authentication.interactiveloginauthentication?view=azure-ml-py) to the SDK and then the user can pass that auth object to the `auth` parameter of `get_workspace()`, correct?

**Comment by diondrapeck** [comment]
@mx-iao Yep!
