### ISSUE TITLE
Timeout while registering model with multiple files

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#264]
I'm trying to register a bunch of objects related to my model.
All works fine when I register only one file using this code:

```
model <- register_model(ws, 
                        model_path = "../models",
                        child_paths = list(
                          "file_01.rds"
                        ),
                        model_name = "my_model",
                        description = "my first model")
```

But if I try to upload multiple files in this way:

```
model <- register_model(ws, 
                        model_path = "../models",
                        child_paths = list(
                          "file_01.rds",
                          "file_02.rds"
                        ),
                        model_name = "my_model",
                        description = "my first model")
```

I get the following error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   AzureHttpError: Operation could not be completed within the specified time. ErrorCode: OperationTimedOut
> <?xml version="1.0" encoding="utf-8"?><Error><Code>OperationTimedOut</Code><Message>Operation could not be completed within the specified time.
> RequestId:bfaab081-301e-0007-57a0-f0d1d3000000
> Time:2020-03-02T14:42:12.1932660Z</Message></Error> 

Any suggestion to bypass the issue? I really need to register more than one objects.

---------------------------------------------------------------
**UPDATE:**
I managed to upload a single zip file via the web interface.
Trying something like this:
```
model <- register_model(ws,
                        model_path = "../models/clustering-model.zip",
                        model_name = "timeseries_clustering_model_test",
                        description = "my first model")
```

I got the same error.

**Comment by mx-iao** [comment]
How large is file_02.rds? There is a 60 second timeout (default HTTP request timeout) with registering the model via the SDK so likely the file(s) are too big and need to be compressed. To clarify: you are able to upload the zip file via the web interface but not with the SDK right? Let me follow up to see if the web interface has different timeouts

**Comment by mx-iao** [comment]
Actually how large are both files?

**Comment by lucazav** [comment]
The zip file contains 5 rds files. I uploaded the entire zip file via the web UI with success. Here the sizes of files:

- clustering-model.zip (3375 KB)
- file_01.rds (1476 KB)
- file_02.rds (1972 KB)
- file_03.rds (15 KB)
- file_04.rds (5 KB)
- file_05.rds (3 KB)
