### ISSUE TITLE
Unhealthy state of ACI after trying to deploy a model from R SDK

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#265]
I'm trying to deploy a model in this way:

```
model <- get_model(ws, name = "timeseries_clustering")

r_env <- r_environment( name = "timeseries_clust_env",
                        cran_packages = c("dplyr", "purrr") )

inference_config <- inference_config(
  entry_script = "inference_clustering.R",
  source_directory = ".",
  environment = r_env)

aci_config <- aci_webservice_deployment_config(cpu_cores = 1, memory_gb = 0.5)

aci_service <- deploy_model(ws, 
                            'timeseries-clustering-test', 
                            list(model), 
                            inference_config, 
                            aci_config)

wait_for_deployment(aci_service, show_output = TRUE)

```

After waiting for a long time, I got this error:

> WebserviceException: WebserviceException:
> 	Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
> Operation ID: d2b4bd1c-5ba5-459c-90e7-c45a773875e5
> More information can be found using '.get_logs()'
> Error:
> {
>   "code": "DeploymentTimedOut",
>   "statusCode": 504,
>   "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
> }

**Comment by mx-iao** [comment]
Hi @lucazav can you run [`get_webservice_logs()`](https://azure.github.io/azureml-sdk-for-r/reference/get_webservice_logs.html) and let us know what you're getting?

**Comment by lucazav** [comment]
Thank you @mx-iao for your hint in using `get_webservice_logs()`.
Looking at logs I see a wrong way to access to the registered model file.
As I pointed out at [Issue264](https://github.com/Azure/azureml-sdk-for-r/issues/264), I succeeded to register the model manually using the web UI and passing a single zip file.

Now I'm using this code into the scoring script to unzip and then use the single RDS files:
```
model_path <- Sys.getenv("AZUREML_MODEL_DIR")
  
# Load model objects from the zip file
obj_01_conn <- unz( file.path(model_path, "clustering-model.zip"), "obj_01.rds" )
obj_01 <- readRDS( gzcon(obj_01_conn) )
close(obj_01_conn)
  
obj_02_conn <- unz( file.path(model_path, "clustering-model.zip"), "obj_01.rds" )
obj_01 <- readRDS( gzcon(obj_01_conn) )
close(obj_01_conn)
```

Is it the right way to access to the zip file and then extract the single objects?

**Comment by mx-iao** [comment]
Yes, you will need to first unzip the zipped model file before accessing the individual files inside, since the registered model right now is only the zip file. `file.path(model_path, 'clustering-model.zip')` is the correct way to get the path to the zipped file.

Here is more information on accessing the correct model path: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-and-where#azureml_model_dir 

I am currently working on enhancing our documentation in the R SDK for the model registration/management bits.

**Comment by lucazav** [comment]
Now the scoring ACI is working like a charm.
Thank you!
