### ISSUE TITLE
Cannot create an AKS Inference Cluster from SDK

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#267]
I'm trying to create an AKS cluster with the following code:

```
aks_target <- create_aks_compute(ws, cluster_name = 'mycluster',
                                 vm_size = "Standard_D3_v2",
                                 agent_count = 3,
                                 location = "West Europe")
```
but I'm getting the following error:

> Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: westeurope, Current Limit: 10, Current Usage: 7, Additional Required: 12, (Minimum) New Limit Required: 19. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/... by specifying parameters listed in the ‘Details’ section for deployment to succeed.

Am I really exceeding the quota with a "simple" AKS cluster like the upon mentioned one?

**Comment by mx-iao** [comment]
@nishankgu can you please take a look at this quota issue

**Comment by nishankgu** [comment]
yes most likely you are exceeding quota. AKS quota comes from all up subscription level compute quota - https://docs.microsoft.com/en-us/azure/machine-learning/how-to-manage-quotas#virtual-machines

Please go to quota blade under subscriptions on the Azure portal, to view the current usage of your quota in your region. In the above specification you are trying to create a produciton AKS cluster - you may alos consider creating a devtest AKS cluster whihc requires fewer nodes for testing purposes - https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-azure-kubernetes-service#create-a-new-aks-cluster

**Comment by mx-iao** [comment]
More comprehensive documentation added with #305; added a quota section in the troubleshooting guide and a model deployment guide.
