### ISSUE TITLE
Warning "No connection could be made because the target machine actively refused it"

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#268]
I'm often get the following warning when loading my workspace objects from my on-premises RStudio:

> WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000209AD2F57B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)'

Is there something to fix by my side?

**Comment by lucazav** [comment]
It seems the problem was the windows firewall.
I disabled it for each profile:

![image](https://user-images.githubusercontent.com/6104437/75779946-e219c180-5d5a-11ea-9e40-44035251c24a.png)

and now I'm not getting those messages.

**Comment by mx-iao** [comment]
I don't believe we've seen this issue before. @diondrapeck can you take a look?

**Comment by diondrapeck** [comment]
Hi @lucazav - Are you working behind a proxy?

**Comment by lucazav** [comment]
Hi @diondrapeck,

I'm using an on-premises VMWare VM, no proxy and I turned off the windows firewall.

**Comment by lucazav** [comment]
I suppose the warnings are due to any VM connection issues, since I don't have any of such message in my Compute Instance
