### ISSUE TITLE
Inference script in an AKS compute target can't resolve the model path as ACI does

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#269]
After trying to develop my model on an existing dev-test AKS compute target (as mentioned [here](https://github.com/Azure/azureml-sdk-for-r/issues/266#issuecomment-593943130)), I get the following error:

>   warnings.warn(x, RRuntimeWarning)
> /opt/miniconda/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  cannot open zip file 'azureml-models/timeseries_clustering/1/clustering-model.zip'

I'm using the same inference script I've used when deploying the model on the ACI as mentioned [here](https://github.com/Azure/azureml-sdk-for-r/issues/265#issuecomment-593557471).

Is there another logic for AKS to resolve model paths?

**Comment by mx-iao** [comment]
Model path resolution should be the same for both ACI and AKS deployments. Are there additional logs you can share? @heemanshusuri can you take a look?

**Comment by lucazav** [comment]
The inference script is like the following:

```
init <- function()
{
  model_path <- Sys.getenv("AZUREML_MODEL_DIR")
  
  # Load model objects from the zip file
  object_01_conn <- unz( file.path(model_path, "clustering-model.zip"), "object_01.rds" )
  object_01 <- readRDS( gzcon(object_01_conn) )
  close(object_01_conn)
  ...
```
I registered the model manually using the web UI. The zip file contains multiple RDS objects.

**Comment by lucazav** [comment]
I tried again with a different inference script (that works fine using ACI) and I got the same error I said before:

> /opt/miniconda/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  cannot open zip file 'azureml-models/timeseries_clustering_2/1/clustering-model-2.zip'

Any suggestion, please?

**Comment by mx-iao** [comment]
@lucazav Following up with the team right now

**Comment by lucazav** [comment]
Hi @mx-iao,

any news on this issue?

Thank you.

**Comment by lucazav** [comment]
Is this solved with the new Python SDK?
Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mx-iao** [comment]
@lucazav let me follow up with you offline
