### ISSUE TITLE
expose cluster_purpose parameter for create_aks_compute()

### ISSUE THREAD

**Issue by mx-iao** [Azure/azureml-sdk-for-r#270]
Expose `cluster_purpose` parameter for `create_aks_compute()` method to differentiate between setting up devtest and fastprod clusters.

Related issue: #266

**Comment by diondrapeck** [comment]
@mx-iao - do we want to add the [ClusterPurpose](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.compute.aks.akscompute.clusterpurpose?view=azure-ml-py) object as well?
