### ISSUE TITLE
hyperparameter-tune-with-keras vignette fails due to reticulate version

### ISSUE THREAD

**Issue by sdonohoo** [Azure/azureml-sdk-for-r#274]
**Describe the bug**
Running the [hyperparameter-tune-with-keras vignette](https://github.com/Azure/azureml-sdk-for-r/tree/master/vignettes/hyperparameter-tune-with-keras) example fails for all hyperparameter tasks at:

`install_keras()`

in cifar10_cnn.R. The error is:

`Error in conda_install(envname, packages = packages, conda = conda, ...) : 
  unused argument (python_version = conda_python_version)`

Searching on this error with `install_keras()`, it is usually associated with a reticulate version incompatibility. Updating reticulate seems to usually, but inconsistently, solve the problem. Running the base docker image for the R SDK interactively, I can solve the issue by updating/installing reticulate to 1.14 and restarting R.

The base R SDK docker image installs r-reticulate using conda rather than installing from CRAN. This installs reticulate v1.12. As far as I can tell, that is the latest version available using conda. 

Modifying the base Dockerfile and removing r-reticulate from:

`RUN conda install -c r -y r-essentials=3.6.0 r-reticulate rpy2 r-remotes r-e1071 r-optparse  && conda clean -ay && pip install --no-cache-dir azureml-defaults`

appears to solve the problem as the subsequent installation of the `azuremlsdk` from CRAN installs reticulate 1.14 along with it. 

**To Reproduce**
Clone https://github.com/Azure/azureml-sdk-for-r repo in Azure ML Compute Instance and run hyperparameter-tune-with-keras vignette.

**Expected behavior**
Successful installation of keras and run of hyperparameter-tune-with-keras example.

**Additional context**
Troubleshooting was done using the Dockerfile definition created by the r_environment() function:
`FROM mcr.microsoft.com/azureml/base:openmpi3.1.2-ubuntu16.04`
`RUN conda install -c r -y r-essentials=3.6.0 r-reticulate rpy2 r-remotes r-e1071 r-optparse  && conda clean -ay && pip install --no-cache-dir azureml-defaults`
`ENV TAR /bin/tar`
`RUN R -e "remotes::install_cran('azuremlsdk', repos = 'https://cloud.r-project.org/', upgrade = FALSE)"`

obtained by running:

`library(azuremlsdk)`
`ws <- load_workspace_from_config()`
`renv <- r_environment(ws)`
`renv$docker$base_dockerfile`

**Comment by mx-iao** [comment]
Ah yes, good catch! @diondrapeck @heemanshusuri can we remove the explicit r-reticulate installation and have the azuremlsdk CRAN installation handle the dependency as Scott mentioned?

**Comment by revodavid** [comment]
This appears to be resolved in v0.6.85. I was able to run hyperparameter-tune-with-keras.Rmd without error.
