### ISSUE TITLE
Run in queue for 1 hour and half

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#275]
I've executed a run than is in queue for 1 hour and half:

![image](https://user-images.githubusercontent.com/6104437/76093321-0d054f00-5fc1-11ea-91d0-c6871d080358.png)

Why all this waiting?

**Comment by diondrapeck** [comment]
@lucazav - Do you have any other runs going at the same time? Check your experiments and compute on your Workspace.

**Comment by lucazav** [comment]
No other runs at same time. After 2 hours the run started.

**Comment by diondrapeck** [comment]
Sorry about the delay! This was likely an intermittent cluster availability issue on the Compute side. I'm glad your run did finally start.
