### ISSUE TITLE
error in get_workspace_details()

### ISSUE THREAD

**Issue by mx-iao** [Azure/azureml-sdk-for-r#289]
Following error when calling get_workspace_details():
```
> get_workspace_details(ws)
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0
```
Seems to be due to how we return the result as a data frame. @diondrapeck perhaps we should revert back to return it as is (a named list) to avoid introduction of these kinds of issues?

**Comment by diondrapeck** [comment]
@mx-iao Are we only seeing this with workspace or do we need to revert all data frames back to named lists? In [his original PR](https://github.com/Azure/azureml-sdk-for-r/pull/136/files), @heemanshusuri introduced DFs for run and compute as well.

**Comment by mx-iao** [comment]
> @mx-iao Are we only seeing this with workspace or do we need to revert all data frames back to named lists? In [his original PR](https://github.com/Azure/azureml-sdk-for-r/pull/136/files), @heemanshusuri introduced DFs for run and compute as well.

Let me double check and get back to you

**Comment by mx-iao** [comment]
@diondrapeck I'm only see this with workspace details, but I think we can still revert the other two - in case something similar ever happens there too?

**Comment by mx-iao** [comment]
As a workaround:
```
ws <- load_workspace_config()
ws$get_details()
```
