### ISSUE TITLE
view_run_details() is not working

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#292]
I've just executed a run using the last Python SDK (1.1.5.1) on my client:

```
est <- estimator(source_directory = ".",
                 entry_script = "training_clustering.R",
                 cran_packages = c("tidyverse", "dtwclust", "clue", "smooth", "RODBC"),
                 custom_docker_image = "lucazav/r-sdk-docker-img:v2",
                 script_params = list("--data_folder" = ds$path(target_path)),
                 compute_target = compute_target )

run <- submit_experiment(exp, est)
view_run_details(run)
```
When executing `view_run_details(run)`, I get the following error:

> [1] "Listening on 127.0.0.1:6389"
> Warning: Error in py_call_impl: AttributeError: 'str' object has no attribute '_get_service_client'
> 
> Detailed traceback: 
>   File "/anaconda/envs/r-reticulate/lib/python3.8/site-packages/azureml/core/workspace.py", line 479, in get
>     result_dict = Workspace.list(subscription_id, auth=auth, resource_group=resource_group)
>   File "/anaconda/envs/r-reticulate/lib/python3.8/site-packages/azureml/core/workspace.py", line 540, in list
>     workspaces_list = Workspace._list_legacy(auth, subscription_id=subscription_id)
>   File "/anaconda/envs/r-reticulate/lib/python3.8/site-packages/azureml/core/workspace.py", line 1101, in _list_legacy
>     raise e
>   File "/anaconda/envs/r-reticulate/lib/python3.8/site-packages/azureml/core/workspace.py", line 1094, in _list_legacy
>     workspace_autorest_list = _commands.list_workspace(auth, subscription_id=subscription_id,
>   File "/anaconda/envs/r-reticulate/lib/python3.8/site-packages/azureml/_project/_commands.py", line 395, in list_workspace
>     return ml_workspace_ [... truncated]
>   89: <Anonymous>

and nothing is shown in the Viewer.

**Comment by mx-iao** [comment]
Is this on the compute instance or your local RStudio?

**Comment by lucazav** [comment]
On my local RStudio I get the error as soon as I run the estimator.
On the compute instance I get the run details on the first run. After the first refresh I get the error.

**Comment by diondrapeck** [comment]
Hi @lucazav - This is an issue I'm working on - we're experiencing it with our tests as well. The root is an issue with authentication. Once I've fixed it, I will close this issue.
