### ISSUE TITLE
log_table_to_run() causes my run to fail

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#293]
In my training code I have this command:

```
log_table_to_run( "My table",
                  split.default( my_table_df, names(my_table_df)) )
```
where `my_table_df` is a tibble.
When executed, the run fails with the following error in the `70_driver_log.txt` log file:

> Error in py_call_impl(callable, dots$args, dots$keywords) : KeyError: 0
> 
> Detailed traceback: 
>   File "/opt/miniconda/lib/python3.7/site-packages/azureml/core/run.py", line 1477, in log_table
>     self._client.log_table(name, value, description=description)
>   File "/opt/miniconda/lib/python3.7/site-packages/azureml/_run_impl/run_history_facade.py", line 222, in log_table
>     self._log_metric(metric)
>   File "/opt/miniconda/lib/python3.7/site-packages/azureml/_run_impl/run_history_facade.py", line 284, in _log_metric
>     self.metrics.log(metric)
>   File "/opt/miniconda/lib/python3.7/site-packages/azureml/_restclient/metrics_client.py", line 243, in log
>     metric_dto = metric.create_metric_dto()
>   File "/opt/miniconda/lib/python3.7/site-packages/azureml/core/_metrics.py", line 284, in create_metric_dto
>     value = self.to_cells()
>   File "/opt/miniconda/lib/python3.7/site-packages/azureml/core/_metrics.py", line 339, in to_cells
>     for key, value in zip(keys, values):
>   File "/opt/miniconda/lib/python3.7/site-packages/azureml/core/_metrics
> Calls: log_table_to_run -> <Anonymous> -> py_call_impl
> Execution halted

-------

For a usability point of view, it's better that the `log_table_to_run()` function gets a dataframe/tibble as input parameter. A named list for a table is really uncomfortable.

--------
**UPDATE**

I also tried to add a log to a run from my client in this way:

```
run <- get_run(exp, run_id = "my-run-id")

run$download_file("outputs/my_obj.rds")
my_obj <- readRDS("my_obj.rds")

log_table_to_run( "My Table",
                  split.default(my_obj$my_df, names(my_obj$my_df)),
                  run = run)
```
and I got the following error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : KeyError: 0 
> 
> 15
> stop(structure(list(message = "KeyError: 0", call = py_call_impl(callable, 
>     dots$args, dots$keywords), cppstack = NULL), class = c("Rcpp::exception", 
> "C++Error", "error", "condition"))) 
> 14
> pandas at hashtable_class_helper.pxi#1627
> 13
> pandas at hashtable_class_helper.pxi#1619
> 12
> pandas at index.pyx#138
> 11
> pandas at index.pyx#111
> 10
> get_loc at base.py#2648
> 9
> __getitem__ at frame.py#2800
> 8
> to_cells at _metrics.py#339
> 7
> create_metric_dto at _metrics.py#284
> 6
> log at metrics_client.py#243
> 5
> _log_metric at run_history_facade.py#284
> 4
> log_table at run_history_facade.py#222
> 3
> log_table at run.py#1477
> 2
> run$log_table(name, value, description) 
> 1
> log_table_to_run("My Table", split.default(my_obj$my_df, 
>     names(my_obj$my_df)), run = run)

**Comment by diondrapeck** [comment]
@lucazav - could you please try this with a data.frame rather than a tibble? Please let me know if the error persists.

**Comment by lucazav** [comment]
Hi @diondrapeck ,
I'm getting the same error using a data frame, since the `split.default()` function returns a list regardless you use a tibble or a dataframe.

**Comment by lucazav** [comment]
I found the "bug": I need to transform all the list elements in vectors, since the split.default() transform a dataframe in a list of dataframes of 1 column. So the working code is:

```
log_table_to_run( "My Table",
                  split.default(my_obj$my_df, names(my_obj$my_df)) %>%
                     map(~ pull(.)),
                  run = run)
```

As I said before, having a `log_table_to_run()` function that accepts also dataframes would be great.

**Comment by diondrapeck** [comment]
Glad you got it working! 

The reason the function requires a named list is because the Python backend uses dictionary, and named lists are the R equivalent of dictionaries. Moving to dataframes would require extra processing before handing over to Python.

We appreciate the feedback though. We obviously do not want the SDK to feel unnatural for R users, so we're continually working to strike a balance between user familiarity and efficiency.
