### ISSUE TITLE
Error in rendering a logged picture from the UI

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#294]
I've executed a run with success, in which few pictures are logged using `log_image_to_run()`.
When trying to rendering them using the UI I get the following error:

![image](https://user-images.githubusercontent.com/6104437/77231180-99a33600-6b99-11ea-8d0b-f3990165456f.png)

**Comment by diondrapeck** [comment]
Hi @lucazav - I've reached out to the Workspace UI team for help (as this is not an RStudio issue per se). I will update you when I learn more.

**Comment by mx-iao** [comment]
@lucazav can you share the code you used to log the images? Thanks

**Comment by lucazav** [comment]
@mx-iao here the code:

```
plt_clustering <- plot(pc_ens_centroid)

log_image_to_run("Clustered time series and centroids for global clustering", plot = plt_clustering)
```

where `pc_ens_centroid` is a `cl_medoid {clue}` object.

**Comment by mx-iao** [comment]
Not able to repro - please reopen if still an issue.
