### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords)

### ISSUE THREAD

**Issue by VincentTennanty** [Azure/azureml-sdk-for-r#297]
Hi guys
Im having some trouble deploying my first webservice.
When I run deploy_model() Im getting the following error.

Error in py_call_impl(callable, dots$args, dots$keywords)
Evaluation error: Evaluation error: Unable to convert R object to Python type..

Im trying to use the forecast package, so that my webservice will forecast  7 days of data  thats passed through.
Also can anyone confirm, when a model is registered, under Model details in azure ML should the framework be Custom or R framework?

**Comment by mx-iao** [comment]
Hi @VincentTennanty, 
Are you able to provide a minimally reproducible example of your score.R code?

Also yes, the model framework will be "Custom". [Here](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.model.framework?view=azure-ml-py) is a list of the model framework types that Azure ML supports for no-code deployment; other model formats are considered custom (this means that you have to provide your own inference code).

**Comment by mx-iao** [comment]
We've also added a more in-depth documentation on model deployment: https://azure.github.io/azureml-sdk-for-r/articles/guides/deploying-models.html

**Comment by mx-iao** [comment]
Closing, please reopen if needed.
