### ISSUE TITLE
Something similar to the Python logging class

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#299]
Is there something similar to the `logging` class like [this](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-debug-pipelines#logging-options-example) in the R SDK?
Is `message()` enough to write to log files?

---------------

**UPDATE**

Is this enough?
```
logger <- azureml$core$logging$getLogger()

logger$debug("Debug message")
logger$error("Error message")
```

**Comment by diondrapeck** [comment]
Hi @lucazav, the linked example is using Python's built-in `logging` library. There's not a azureml.core.logging.getLogger() that's used. 

I would recommend either finding an analogous logging package for R.
