### ISSUE TITLE
Can't register a model from a run

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#300]
I'm trying to register a model after a run has finished in this way from my Compute Instance:

```
experiment_name <- "my-clustering"
exp <- experiment(ws, experiment_name)

run <- get_run(exp, run_id = "my-clustering_1584804762_557f3721")

# Just checking that 'outputs/clusterings.rds' exists
run$get_file_names()

model <- run$register_model(ws, 
                            model_path = "outputs/clusterings.rds", 
                            model_name = "Test registered model",
                            description = "Test registered model" )
```

I'm getting the following error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   TypeError: register_model() got multiple values for argument 'model_name'

-----------------
**UPDATE**

I found the `register_model_from_run()` wrapper function. Using it in the following way:

```
register_model_from_run(run = run,
                        model_path = "outputs/clusterings.rds", 
                        model_name = "clusterings",
                        description = "Test registered model")
```

> gives me the following error:
>  Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   TypeError: _register_with_asset() got an unexpected keyword argument 'run' 

The definition of the run's `register_model()` function says that it expects a workspace in input:
![image](https://user-images.githubusercontent.com/6104437/77654673-a517a800-6f71-11ea-97b9-c860273e1647.png)

If I get the source code of the wrapper function `register_model_from_run()`, I see the same `register_model()` function expects a run as input:
![image](https://user-images.githubusercontent.com/6104437/77654894-f32cab80-6f71-11ea-93d6-bd7b7f59948a.png)

**Comment by diondrapeck** [comment]
Hi @lucazav - `register_model` and `register_model_from_run` are different functions. `register_model` registers a model to a workspace which is why you see it in the definition. `register_model_from_run` doesn't need a workspace, it just wants the run. So your original line `run$register_model(ws,....)` should be `run$register_model(run, ...)`.

**Comment by mx-iao** [comment]
I believe this is related to issue #302

**Comment by lucazav** [comment]
Hi @diondrapeck ,
if so, the tooltip on `run$register_model()` is totally misleading, so I think it should be forced to show `run` and not `workspace`.
That said, my code using `register_model_from_run()` is not working. So I suppose there is an issue, as @mx-iao has pointed out.

**Comment by diondrapeck** [comment]
@mx-iao I don't think they're related.

**Comment by mx-iao** [comment]
I think the initial issue wasn't, but I believe `register_model_from_run()` won't work if the user doesn't specify the `datasets` argument

**Comment by diondrapeck** [comment]
Oh, yes. You may be experiencing that issue if it's still not working. Sorry, @mx-iao I thought you were referring to the original issue. 

@lucazav I just created a PR to solve the issue with `register_model_from_run`, so once that's in, your issue should be resolved. Sorry about the bug!
