### ISSUE TITLE
Error returned by deploy_model() function: 'InferenceConfig' object has no attribute 'id'

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#301]
I'm trying to deploy a new model using ACI. I've already used the following code before with success:

```
r_env <- r_environment( name = "timeseries_clust_env",
                        cran_packages = c("dplyr", "tibble", "purrr") )

model_20_days <- get_model(ws, name = "timeseries-clust-20-days")


inference_config_20_days <- inference_config(
  entry_script = "inference_clustering_20_days.R",
  source_directory = ".",
  environment = r_env)

aci_config <- aci_webservice_deployment_config(cpu_cores = 1, memory_gb = 2,
                                               auth_enabled = TRUE, location = "West Europe")

aci_service_20_days <- deploy_model(ws,
                             'timeseries-clustering-20-days',
                             list(inference_config_20_days),
                             inference_config_20_days,
                             aci_config)
```
Now, when running the `deploy_model()` function, I'm getting the following error:

>  Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   AttributeError: 'InferenceConfig' object has no attribute 'id' 
> 
> 5
> stop(structure(list(message = "AttributeError: 'InferenceConfig' object has no attribute 'id'", 
>     call = py_call_impl(callable, dots$args, dots$keywords), 
>     cppstack = NULL), class = c("Rcpp::exception", "C++Error", 
> "error", "condition"))) 
> 4
> _deploy_with_environment at model.py#1907
> 3
> deploy at model.py#1673
> 2
> azureml$core$Model$deploy(workspace, name, models, inference_config, 
>     deployment_config, deployment_target) 
> 1
> deploy_model(ws, "timeseries-clustering-20-days", list(inference_config_20_days), 
>     inference_config_20_days, aci_config) 

I tried the previous code installing the last R SDK available today on Github and installing also the Python SDK 1.2.0 in my Compute Instance.

**Comment by heemanshusuri** [comment]
Hi @lucazav 

There is a bug in your deploy_model() call. The third parameter is a list of models and you have passed a list of inference config. It should be:

```
aci_service_20_days <- deploy_model(ws,
                             'timeseries-clustering-20-days',
                             list(model_20_days),
                             inference_config_20_days,
                             aci_config)

```

**Comment by lucazav** [comment]
Ouch!! A copy&past error. May be I'm too tired.
Thank you very much!
