### ISSUE TITLE
register_model() fails on missing datasets argument

### ISSUE THREAD

**Issue by sdonohoo** [Azure/azureml-sdk-for-r#302]
**Describe the bug**
Attempting to register a model using register_model():

![image](https://user-images.githubusercontent.com/1457586/77780234-a9030300-7021-11ea-8d42-c3715c2d9e7e.png)

**To Reproduce**
Use register_model() or register_model_from_run() without setting the datasets argument.

**Expected behavior**
Successful registration of the model. This code worked a couple of weeks ago under a previous SDK install. After refreshing this morning to fix another issue, the registration no longer works.

**Additional context**
register_model() defines the datasets argument as optional with a NULL default but the function does not check for NULL and attempts to unlist an expected list of datasets.

**Comment by mx-iao** [comment]
Thanks for the catch, Scott! We'll fix this ASAP. @diondrapeck can you create a fix for this?
