### ISSUE TITLE
github_packages option doesn't work for RScriptStep

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#329]
After I tried to use a custom Docker image with no success (see [here](https://github.com/Azure/azureml-sdk-for-r/issues/328)), I tried to update the `azuremlsdk` package from Github using the `github_packages` parameter in _RScriptStep_ in the following way:

```
trainStep = RScriptStep(
    name = "train_step",
    script_name="training_clustering.R",
    arguments=["--my_tabular_ds", inputData, "--output", outputData],
    inputs=[inputData],
    outputs=[outputData],
    compute_target=compute_target,
    source_directory = './',
    cran_packages = ["optparse", "tidyverse", "lubridate", "dtwclust", "clue", "smooth"],
    #custom_docker_image = "lucazav/r-sdk-docker-img:v2",
    github_packages = ["Azure/azureml-sdk-for-r"]
)
```

I'm getting the following error:

> The downloaded source packages are in
> 	‘/tmp/Rtmp4y9Sbo/downloaded_packages’
> Updating HTML index of packages in '.Library'
> Making 'packages.html' ... done
> Error in get0(oNam, envir = ns) : 
>   lazy-load database '/opt/miniconda/lib/R/library/pkgbuild/R/pkgbuild.rdb' is corrupt
> Calls: <Anonymous> ... safe_build_package -> :: -> getExportedValue -> get0
> In addition: Warning message:
> In get0(oNam, envir = ns) : internal error -3 in R_decompress1
> Execution halted
> 2020/04/28 12:08:43 mpirun version string: {
> Intel(R) MPI Library for Linux* OS, Version 2018 Update 3 Build 20180411 (id: 18329)
> Copyright 2003-2018 Intel Corporation.
> }
> 2020/04/28 12:08:43 MPI publisher: intel ; version: 2018

Is there anything I can do?

**Comment by mx-iao** [comment]
Hi @lucazav, we just submitted a fix for this issue and it should be in the next release of the Python SDK.

**Comment by lucazav** [comment]
Thank you very much!

**Comment by mx-iao** [comment]
@lucazav this issue should be addressed now. Please reopen if you continue to face this issue.

**Comment by heinsuoleo** [comment]
> 
> 
> @lucazav this issue should be addressed now. Please reopen if you continue to face this issue.

Version 1.7.0 of the azureml SDK doesn't have RScriptStep.

**Comment by lucazav** [comment]
Hi @mx-iao, hi @heemanshusuri,

I run the same code again, but I got the same error.

I also tried to point to a custom docker image as following:

```
trainStep = RScriptStep(
    name = "train_step",
    script_name="training_clustering.R",
    arguments=["--my_tabular_ds", inputData, "--output", outputData],
    inputs=[inputData],
    outputs=[outputData],
    compute_target=compute_target,
    source_directory = './test',
    custom_docker_image = "lucazav/ts-clustering-img:v1"
)
```

but I got the following error:
![image](https://user-images.githubusercontent.com/6104437/87921344-b766a600-ca7a-11ea-84cb-1af0071671c6.png)

even if that image is [available on Docker Hub](https://hub.docker.com/r/lucazav/ts-clustering-img/tags).

**Comment by mx-iao** [comment]
@lucazav can you do this:
```python
runconfig = RunConfiguration()
runconfig.environment.docker.enabled = True
runconfig.environment.docker.base_image = "my-custom-image"
step = RScriptStep(script_name='test.R', 
                   name='test-step', 
                   compute_target=compute, 
                   source_directory='.',
                   runconfig=runconfig,
                   allow_reuse=True)
experiment = Experiment(ws, 'rscriptstep-test')
run = experiment.submit(pipeline)
```

**Comment by mx-iao** [comment]
@heinsuoleo RScriptStep was added since v 1.0.65. Try upgrading to latest azureml-sdk (1.10.0) if you're having issues

**Comment by mx-iao** [comment]
With latest version of the Python SDK (1.12.0), below is an example of the recommended way to specify CRAN & GitHub packages for your RScriptStep:

```Python
from azureml.core import Experiment
from azureml.pipeline.steps import RScriptStep
from azureml.core.runconfig import RunConfiguration
from azureml.core.environment import Environment, RSection, RCranPackage, RGitHubPackage

rc = RunConfiguration()
rc.framework = 'R'

cran_pkg = RCranPackage()
cran_pkg.name = 'ggplot2'
github_pkg = RGitHubPackage()
github_pkg.repository = 'Azure/azureml-sdk-for-r'
rc.environment.r = RSection()
rc.environment.r.cran_packages = [cran_pkg]
rc.environment.r.github_packages = [github_pkg]
rc.environment.docker.enabled = True

step = RScriptStep(script_name='test.R',
                   name='test-step',
                   compute_target=compute,
                   runconfig=rc,
                   source_directory='.')

pipeline = Pipeline(workspace=ws, steps=[step])
pipeline.validate()

experiment = Experiment(ws, 'your-experiment-name')
run = experiment.submit(pipeline)
```

For an example of using custom Docker image, see #328
