### ISSUE TITLE
Issues with get_workspace

### ISSUE THREAD

**Issue by chmitch** [Azure/azureml-sdk-for-r#330]
I'm a guest user on another organizations Azure Subscription.   I have contributor permissions on the resource group that contains the Azure Machine Learning workspace.  When I attempt to call get_workspace, I get the message:

"You are currently logged-in to <my company's aad tenant id> tenant. You don't have access to <customer's subscription ID> subscription, please check if it is in this tenant.

When I'm using the browser I can navigate to the workspace just fine and do things like create compute, create automl experiments, and also work with datastores and datasets.   However, I can't do anything in the SDK because I can't get past authenticating to the workspace.

If I have contributor access to the workspace, does it matter what subscription I authenticate against?

**Comment by lucazav** [comment]
Hi @chmitch ,

I suppose you need to login using the interactive authentication and passing the proper tenant id:

```
auth <- interactive_login_authentication( tenant_id="<your-tenant-id>" )
ws <- get_workspace( "<your-workspace-name>",
                     subscription_id = "<your-subscription-id>", 
                     resource_group = "<your-resource-group>",
                     auth = auth )
```

Please, refer to [this blog post](https://medium.com/microsoftazure/how-to-authenticate-into-azure-machine-learning-using-the-r-sdk-3ff930697bd1) for more details about authentication using the R SDK.

**Comment by realAngryAnalytics** [comment]
I have had the same issue and even with interactive login I am not successful. Note that this is also a problem in the Python SDK. I had to resort to using service principal authentication.

https://azure.github.io/azureml-sdk-for-r/reference/service_principal_authentication.html
