### ISSUE TITLE
r_environment() function is not working in the latest release

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#331]
I've just installed the latest version of `azuremlsdk` from Github and I've also installed Python SDK 1.4.0.
I'm trying to run this code:

```
r_env <- r_environment( name = "timeseries_clust_env",
                        cran_packages = c("dplyr", "tibble", "purrr") )
```

I'm getting the following error:

> Error: $ operator is invalid for atomic vectors

**Comment by diondrapeck** [comment]
Hi Luca, a few weeks ago, the expected value for the cran_packages param was changed in the GitHub release to allow for repo and version specification. This is also true for estimators.

See [the doc page of `r_environment`](https://azure.github.io/azureml-sdk-for-r/reference/r_environment.html) to see what the function expects, and also, [here's](https://azure.github.io/azureml-sdk-for-r/reference/cran_package.html) the doc page of the new `cran_package` param you'll need including an example.
