### ISSUE TITLE
AutoMLConfig() equivalent in SDK

### ISSUE THREAD

**Issue by morganvill** [Azure/azureml-sdk-for-r#332]
Hello,

is there an equivalent for AutoMLConfig() Python SDK function from Azure in R SDK ?

If not, how can I use AutoML with R SDK ?

Thanks.

**Comment by mx-iao** [comment]
Hi @morganvill,
We do not have native R support for AutoML, since the implementation of the AutoML capabilities is closely tied to Python. One option you can try is to use Auto ML & export the models to ONNX format;   ONNX has an [R API](https://onnx.ai/onnx-r/) you can use for inference with the models.

**Comment by joshkyh** [comment]
Hi @mx-iao , 

Regarding AutoML, I am currently implementing an AzureML MLOps platform for my client who uses alot of R.

I am looking to trial training a large number of model types (e.g., neural networks, catboost, xgboost, ensemble) and initiate the call to AzureML from R.

I see that this is currently unavailable and only available via Web Studio or Python, is there a plan to add it to either azureml-sdk-for-r OR the 2.0 CLI.

**Comment by wenxwei** [comment]
Hi @joshkyh ,
Regarding AutoML, we suggest you to create your training job via AutoML UI on AML Studio and outputting the model to ONNX since ONNX has an R API for reference.

**Comment by joshkyh** [comment]
OK thank you. I'll also create a ticket via AzureML Support to see if they have an insight over the product pipeline.

**Comment by joshkyh** [comment]
Update from AzureML Support: "I got an update from our Product Group that as of today we don't have R support for AutoML on our roadmap."
