### ISSUE TITLE
Cannot convert tabular dataset to dataframe

### ISSUE THREAD

**Issue by spontello** [Azure/azureml-sdk-for-r#336]
**Describe the bug**
I am able to successfully create a tabular dataset using the Azure ML R SDK, but I cannot convert the tabular dataset to a dataframe.  I am running RStudio using an Azure ML Workspace compute instance.

azuremlsdk version:
![image](https://user-images.githubusercontent.com/11871091/80821719-8327cb80-8b96-11ea-9a07-f35d449345b9.png)

Error Message:
![image](https://user-images.githubusercontent.com/11871091/80821601-4a87f200-8b96-11ea-93e7-6cb342b69130.png)

**Expected behavior**
Expect to have a dataframe returned

**To Reproduce**
# load library
library(azuremlsdk)

# azuremlsdk::install_azureml(envname = 'r-reticulate')

# connect to workspace
ws <- load_workspace_from_config("Users/stpont/config/config.json")

# connect to Azure Data Lake Storage datastore connection
ds <- get_datastore(ws,"sponteadlsg2")

# create tabular dataset using datastore connection and path
dset <- create_tabular_dataset_from_delimited_files(ds$path('/MLInput.csv'), validate = TRUE,
                                            include_path = FALSE, infer_column_types = TRUE,
                                            set_column_types = NULL, separator = ",", header = TRUE,
                                            partition_format = NULL)

# load data into data frame
df <- load_dataset_into_data_frame(dset)

**Comment by mx-iao** [comment]
Hi @spontello, can you install the R SDK from GitHub with `remotes::install_github('https://github.com/Azure/azureml-sdk-for-r')`. We recently checked in a bug fix regarding this issue. Thanks!

**Comment by spontello** [comment]
I ran the update:
remotes::install_github('https://github.com/Azure/azureml-sdk-for-r')

I also did a re-install of the interface:
azuremlsdk::install_azureml(envname = 'r-reticulate',remove_existing_env = TRUE)

I am now able to create a dataframe!

Thanks!
Steve
