### ISSUE TITLE
Can't read data from Azure SQL Database on-premises

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#345]
I'm trying to read some data from an Azure SQL Database using my on-premises R engine.
I'm using the most recent version of the R SDK and I installed the Python SDK 1.5.0 too.
Here the code:

```
sql_ds <- get_datastore(ws, "my_azuresqldb_dev")
dp <- data_path( sql_ds, "SELECT TOP 1000 * FROM my_schema.my_table" )
tds <- create_tabular_dataset_from_sql_query(dp, query_timeout = 120)
```

I'm getting the following error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   DatasetValidationError: Cannot load any data from the datastore using the SQL query "<azureml.data.datapath.DataPath object at 0x00000255AA3844A8>". Please make sure the datastore and query is correct.
> Could not connect to specified database.|session_id=ddb86695-b4c6-43f1-9007-96f7797507d8 
> 
> 3 stop(structure(list(message = "DatasetValidationError: Cannot load any data from the datastore using the SQL query \"<azureml.data.datapath.DataPath object at 0x00000255AA3844A8>\". Please make sure the datastore and query is correct.\nCould not connect to specified database.|session_id=ddb86695-b4c6-43f1-9007-96f7797507d8", 
>     call = py_call_impl(callable, dots$args, dots$keywords), 
>     cppstack = NULL), class = c("Rcpp::exception", "C++Error", 
> "error", "condition"))) 
> 
> 2 azureml$core$dataset$Dataset$Tabular$from_sql_query(query = query, 
>     validate = validate, set_column_types = set_column_types, 
>     query_timeout = as.integer(query_timeout)) 
> 
> 1 create_tabular_dataset_from_sql_query(dp, query_timeout = 120)

Right now I'm facing an issue with the Compute Instance: it can't start. I can't create a new one neither. Could the _create_tabular_dataset_from_sql_query( )_ error be due to an Azure ML down?

------------------------

**UPDATE**
I've just confirmed it's a bug, since now my Compute Instance is working and _create_tabular_dataset_from_sql_query( )_ is working fine there

**Comment by mx-iao** [comment]
What version of azureml-dataprep do you have?

**Comment by mx-iao** [comment]
Closing, let's track at #347
