### ISSUE TITLE
azureml-dataprep[pandas] not updated

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#347]
I'm trying to read some data from an Azure SQL Database on the Compute Instance.
I'm using the most recent version of the R SDK and I installed the Python SDK 1.5.0 too.
Here the code:

```
sql_ds <- get_datastore(ws, "my_azuresqldb_dev")
dp <- data_path( sql_ds, "SELECT TOP 1000 * FROM my_schema.my_table" )
tds <- create_tabular_dataset_from_sql_query(dp, query_timeout = 120)
df <- load_dataset_into_data_frame(tds)
```

I get the following error:

> /anaconda/envs/r-reticulate/lib/python3.8/site-packages/azureml/dataprep/api/dataflow.py:722: UserWarning: Your pandas and pyarrow versions are incompatible. Please install pyarrow>=0.12.0 for improved performance of to_pandas_dataframe. You can ensure the correct version is installed by running: pip install azureml-dataprep[pandas].
>   warnings.warn('Your pandas and pyarrow versions are incompatible. '
> sys:1: FutureWarning: RangeIndex._start is deprecated and will be removed in a future version. Use RangeIndex.start instead
> sys:1: FutureWarning: RangeIndex._stop is deprecated and will be removed in a future version. Use RangeIndex.stop instead
> sys:1: FutureWarning: RangeIndex._step is deprecated and will be removed in a future version. Use RangeIndex.step instead

After run this code:

`reticulate::py_install("azureml-dataprep[pandas]", envname = "r-reticulate", pip = TRUE)`

I can get the data into `df`, but there are some errors during the update:

> ERROR: azureml-train-automl-client 1.5.0.post1 has requirement azureml-dataprep<1.6.0a,>=1.4.10a, but you'll have azureml-dataprep 1.6.0 which is incompatible.
> ERROR: azureml-sdk 1.5.0 has requirement azureml-dataprep[fuse]<1.6.0a,>=1.4.10a, but you'll have azureml-dataprep 1.6.0 which is incompatible.
> ERROR: azureml-automl-core 1.5.0.post2 has requirement azureml-dataprep<1.6.0a,>=1.4.10a, but you'll have azureml-dataprep 1.6.0 which is incompatible.

Is there a way to automatically install the updated version of `azureml-dataprep[pandas]` when installing the Python SDK 1.5.0?

**Comment by mx-iao** [comment]
```
azuremlsdk::install_azureml(version = "1.5.0", 
                            envname = "<your conda environment name>",
                            remove_existing_env = TRUE)
```
Specify `remove_existing_env = TRUE`. That should delete your existing env and do a clean install
