### ISSUE TITLE
Error when deploying to AKS and ACI

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#350]
I'm trying to deploy my service to AKS in this way:

```
pkg6 <- cran_package("dplyr")
pkg7 <- cran_package("tibble")
pkg8 <- cran_package("purrr")

r_env <- r_environment( name = "inference_env",
                        cran_packages = list(pkg6, pkg7, pkg8) )

inference_config <- inference_config(
  entry_script = "inference.R",
  source_directory = "./test",
  environment = r_env)

aks_target <- get_compute(ws, "my-aks-prod")

aks_service <- deploy_model(ws,
                            'my-service', 
                            models = list(model),
                            inference_config = inference_config, 
                            deployment_target = aks_target)
```

My inference script is something like this:

```
library(dplyr)
library(tibble)
library(purrr)
library(jsonlite)

init <- function()
{
  ...
  function(data)
  {
    
    my_func <- function(a, b){
      (a + 0.001 - (b + 0.001)) / (a + 0.001)
    }
    ...
  }
}
```

My web service is not deployed and I'm getting the following error:

> Initialized PySpark session.
> Exception in worker process
> Traceback (most recent call last):
>   File "/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
>     worker.init_process()
>   File "/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
>     self.load_wsgi()
>   File "/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
>     self.wsgi = self.app.wsgi()
>   File "/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
>     self.callable = self.load()
>   File "/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
>     return self.load_wsgiapp()
>   File "/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
>     return util.import_app(self.app_uri)
>   File "/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
>     __import__(module)
>   File "/var/azureml-server/wsgi.py", line 1, in <module>
>     import create_app
>   File "/var/azureml-server/create_app.py", line 3, in <module>
>     from app import main
>   File "/var/azureml-server/app.py", line 32, in <module>
>     import main as user_main
>   File "/var/azureml-app/main.py", line 12, in <module>
>     driver_module_spec.loader.exec_module(driver_module)
>   File "/structure/azureml-app/test/_generated_score.py", line 2, in <module>
>     import rpy2.robjects as robjects
> ModuleNotFoundError: No module named 'rpy2'
> Worker exiting (pid: 39)
> Shutting down: Master
> Reason: Worker failed to boot.
> 2020-05-21T13:16:08,213759397+00:00 - gunicorn/finish 3 0
> 2020-05-21T13:16:08,215197495+00:00 - Exit code 3 is not normal. Killing image.

I'm using the latest version of the R SDK

---------------------------------

**UPDATE**
I'm getting the same error using also ACI

**Comment by lucazav** [comment]
I've just tried now to deploy a web service on ACI, and I'm getting this error:

> 2020-06-03T07:56:15,571957905+00:00 - iot-server/run 
> 2020-06-03T07:56:15,573681511+00:00 - rsyslog/run 
> 2020-06-03T07:56:15,579841534+00:00 - gunicorn/run 
> 2020-06-03T07:56:15,581114238+00:00 - nginx/run 
> EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
> 2020-06-03T07:56:15,718772940+00:00 - iot-server/finish 1 0
> 2020-06-03T07:56:15,733813995+00:00 - Exit code 1 is normal. Not restarting iot-server.
> Starting gunicorn 19.9.0
> Listening at: http://127.0.0.1:31311 (14)
> Using worker: sync
> worker timeout is set to 300
> Booting worker with pid: 47
> Initialized PySpark session.
> Exception in worker process
> Traceback (most recent call last):
>   File "/opt/miniconda/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
>     worker.init_process()
>   File "/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
>     self.load_wsgi()
>   File "/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
>     self.wsgi = self.app.wsgi()
>   File "/opt/miniconda/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
>     self.callable = self.load()
>   File "/opt/miniconda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
>     return self.load_wsgiapp()
>   File "/opt/miniconda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
>     return util.import_app(self.app_uri)
>   File "/opt/miniconda/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
>     __import__(module)
>   File "/var/azureml-server/wsgi.py", line 1, in <module>
>     import create_app
>   File "/var/azureml-server/create_app.py", line 3, in <module>
>     from app import main
>   File "/var/azureml-server/app.py", line 32, in <module>
>     import main as user_main
> ModuleNotFoundError: No module named 'main'
> Worker exiting (pid: 47)
> Shutting down: Master
> Reason: Worker failed to boot.
> 2020-06-03T07:56:16,904989264+00:00 - gunicorn/finish 3 0
> 2020-06-03T07:56:16,906471870+00:00 - Exit code 3 is not normal. Killing image.

**Comment by mx-iao** [comment]
@lucazav have you resolved the issues you were seeing?

**Comment by lucazav** [comment]
@mx-iao yes. The problem was due to an artifact in the registered model that was listed in the GUI, but was not into the blob storage. I shared this with the product group and I think now the issue is under analysis.

**Comment by jay2017-git** [comment]
@lucazav Please can you share the step you used to resolve it. I'm having this exact same issue when deploying my ML model on ACI. @mx-iao, I'll be glad if you can help look into it as well.
