### ISSUE TITLE
Cannot set R environment use r_version in r_enviroment

### ISSUE THREAD

**Issue by yowgwowang** [Azure/azureml-sdk-for-r#358]
**Describe the bug**
Cannot set R environment in r_environment. 

**To Reproduce**
pkg1 <- cran_package("tsibble")
pkg2 <- cran_package("fable")
pkg3 <- cran_package("tidyverse")
pkg4 <- cran_package("lubridate")
pkg5 <- cran_package("imputeTS")
pkg6 <- cran_package("fabletools")
pkg7 <- cran_package("robfilter")
pkg8 <- cran_package("vctrs")
pkg9 <- cran_package("robfilter")
pkg10 <- cran_package("feasts")
pkg11 <- cran_package("RODBC")
r_env <- r_environment(name = 'hw_env', version = 2, r_version = "4.0.2", cran_packages = list(pkg1, pkg2, pkg3, pkg4, pkg5, pkg6, pkg7, pkg8, pkg9, pkg10, pkg11))

est <- estimator(source_directory = "../Desktop/project/azure_r_tesseract/",
                 entry_script = "run_storage_enterprise_forecast_wt_RODBC.R",
                 compute_target = compute_target,
                 environment = r_env
                 )
run <- submit_experiment(exp, est)

**Expected behavior**
I tried to submit an experiment on AzureML with user-defined enviroment.
I thought the code above will install the R version 4.0.2 accordingly and proceed to install the following library.
However, I got an error message as the following:

PackagesNotFoundError: The following packages are not available from current channels:
  - r-essentials=4.0.2

**Screenshots**
![image](https://user-images.githubusercontent.com/66694357/87736272-8f322b00-c78c-11ea-9cdb-5d803294d9c9.png)
![image](https://user-images.githubusercontent.com/66694357/87736298-9bb68380-c78c-11ea-9ef3-548832c1167d.png)
![image](https://user-images.githubusercontent.com/66694357/87736311-a2dd9180-c78c-11ea-97a8-9ae78a0da5f0.png)

**Additional context**

**Comment by mx-iao** [comment]
`r_version` is limited to the latest version available on conda (which is what we use for system-managed environments) which is 3.6.0. If you want a later version like 4.0.2 you will have to create and build your own custom Docker image (which you can then specify to the `custom_docker_image` parameter of `r_environment()`.

**Comment by yowgwowang** [comment]
Thanks for the answer!
