### ISSUE TITLE
RScriptStep run_config not behaving as expected

### ISSUE THREAD

**Issue by jakeatmsft** [Azure/azureml-sdk-for-r#359]
**Describe the bug**
When specifying pip packages as Conda Dependencies in the RunConfig, the dependencies are never installed.  I have tried both user_managed dependencies and auto_configured_environment and it seems the default environment is always used. 
Requirement for my R Script is azureml-dataprep[fuse,pandas] to connect to Azureml dataset.
Raw JSON of log shows environment definition is passed correctly, but driver logs show packages are not installed.

**To Reproduce**
Create Run_configuration and specify python packages to install.
pass run_configuration as parameter in RScriptStep.
review logs to confirm 

**Expected behavior**
Expect to see azureml-dataprep[fuse,pandas] installed to container.

**Comment by jakeatmsft** [comment]
Issue looks like the RScriptStep, overwrites or fails to take definition of run_config passed.  I was able to modify the step after it had been defined and it seems to be working:

step1 = RScriptStep(...)
  # set runconfig values after step creation
step1._runconfig.environment.python.user_managed_dependencies = False

**Comment by mx-iao** [comment]
@jakeatmsft 
This issue should be fixed with the latest release of the Python SDK (1.12.0). RunConfiguration object passed into the `runconfig` parameter of RScriptStep should no longer get overwritten. See #328 for an example.
