### ISSUE TITLE
tzdata missing from r-base image

### ISSUE THREAD

**Issue by jakeatmsft** [Azure/azureml-sdk-for-r#360]
**Describe the bug**
When running readr::read_csv error is thrown when parsing datatime fields.  Error is "no Olson database found", which corresponds to missing tzdata library on server. 

**To Reproduce**
Install cran package "tidyverse"
run following R script:
   library(tidyverse)
   default_locale()

**Expected behavior**
No error

**Comment by mx-iao** [comment]
You will have to create a custom image. Here is a related GitHub issue: https://github.com/Azure/azureml-sdk-for-r/issues/260

**Comment by jakeatmsft** [comment]
I have been able to fix this issue using custom dockerfile definition.  After creating the RScriptStep:

step._runconfig.environment.docker.base_image = None
step._runconfig.environment.docker.base_dockerfile = r"""
FROM viennaprivate.azurecr.io/r-base:cpu
RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
"""

I had to modify the runconfig after creating the RScriptStep, as the RScriptStep automatically defines some of these variables and will overwrite them if you try to pass in as runconfig param.

**Comment by mx-iao** [comment]
@jakeatmsft yeah the overwriting is a bug we are currently fixing - you have the correct workaround above.
