### ISSUE TITLE
register_model dataset registration bug

### ISSUE THREAD

**Issue by coolkate3738** [Azure/azureml-sdk-for-r#363]
**Describe the bug**
trying to use datasets option within register_model function in R sdk, it fails for what looks to be an [issue](https://github.com/Azure/azureml-sdk-for-r/issues/284) that was menta to be fixed a little earlier this year, but not fixed yet.
(fyi below runs fine without the datasets functionality )
+bear in mind holdout_data_test class is data.table or data.frame, tried both
**To Reproduce**
model <- register_model(ws, 
                        model_path = model_path, 
                        model_name = "cpm_model",
                        description = "freight cost prediction",
                        datasets = list(tuple("validation", holdout_data_test)))

**Expected behavior**
expected model to be registered without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/7931437/88549265-fb781e80-d017-11ea-8ac5-c7ed70897e1f.png)

**Additional context**

**Comment by mx-iao** [comment]
You need to pass in an Azure ML Dataset, not a data.table or data.frame

**Comment by coolkate3738** [comment]
Hi,
Thank you, could you elaborate on what azure dataset is? :) or how do you covert a data frame to that format?thank you ,

**Comment by lucazav** [comment]
Maybe [this link](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets) can help you.

**Comment by mx-iao** [comment]
Documentation: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets
You can look at this PR for examples of how to use datasets in R: https://github.com/Azure/azureml-sdk-for-r/pull/316
