### ISSUE TITLE
Issue in connecting to workspace from Jupyter Notebook using R SDK

### ISSUE THREAD

**Issue by suko10** [Azure/azureml-sdk-for-r#364]
**Describe the bug**
I have trouble in connecting to ML workspace after creating Azure Computer Instance for the first time. I have config file in the same folder. I tried using both load_workspace_from_config() and get_workspace(). I am able to fix this by using RStudio in compute instance

**To Reproduce**

1) Create a new compute instance and then new Jupyter notebook (R Kernel)
2) Place Config file in the working directory
3) Run following commands
library(azuremlsdk)
ws <- load_workspace_from_config()

4) Command will not finish executing (Stop the kernel and close the notebook)
5) Now open Rstudio from instance and execute same commands
6) Perform interactive authentication
7) Now once again open Jupyter notebook and execute the same commands
8) It connects successfully

**Expected behavior**
I should be able to connect to workspace from Jupyter notebook without going to RStudio

**Screenshots**
![AML_WorkSpace_Issue](https://user-images.githubusercontent.com/68894803/88639935-f7610500-d0da-11ea-8a1f-7ec80d4a9d0f.PNG)

**Additional context**

**Comment by coolkate3738** [comment]
I have the same issue with Databricks notebooks, I have to open "Drivers log" in databricks to get the code and link from there, as it would not output it to the notebook console, so +1 to this

**Comment by mx-iao** [comment]
Closing as dupe, will track with #370
