### ISSUE TITLE
Unable to install xgboost on compute cluster- runs fine on compute instance

### ISSUE THREAD

**Issue by harshbangad** [Azure/azureml-sdk-for-r#365]
**Describe the bug**

Getting an error while installing xgboost on the compute cluster machine. 
When I train my model on the compute instance, the packages install successfully and the model trains successfully as expected. 

Now when I am trying to leverage the same using compute cluster, I get an error. Xgboost tries to upgrade the data.table package and then errors out.
I did try to specify old versions of package for both data.table and xgboost but it still tries to upgrade data.table and errors out (this happens only in compute cluster)

These are the package versions in the compute instance where the code runs successfully-

packageVersion("xgboost")
[1] ‘0.82.0.1’
packageVersion("data.table")
[1] ‘1.12.8’

**Code to reproduce error** (run on compute instance)

pkg1 <-   cran_package("data.table")  # , version = '1.12.8') -- tried with   and without versions, all error out  
pkg2 <-   cran_package("xgboost")    # ,version = '0.82.1')   
pkg3 <-   cran_package("e1071")      
pkg4 <-   github_package("Azure/azureml-sdk-for-r")    
r_env <- r_environment(name =   'signalz' ,
              cran_packages =   list(pkg1,pkg2,pkg3),             
               github_packages =   list(pkg4)      )     

 ##Create an estimator -   TrainingScript will be called   
est <-   estimator(source_directory = "./",   
    entry_script =   "signalztraining.R",  
   compute_target =   compute_target,                  
    environment = r_env)      

###Submit the experiment 
  run <-   submit_experiment(exp,   est)  
 wait_for_run_completion(run,   show_output = TRUE)       
 #It will ask to re enter the Microsoft  credentials. Need to sign in into Browser with the provided credentials

**Session** - We can see it tries to upgrade data.table even after specifying to reinstall older version

The downloaded source packages are in
	â€˜/tmp/RtmpGN0j2t/downloaded_packagesâ€™
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Downloading package from url: https://mran.microsoft.com/snapshot/2020-07-28/src/contrib/xgboost_1.1.1.1.tar.gz
lattice    (0.20-38 -> 0.20-41) [CRAN]
stringi    (1.4.3   -> 1.4.6  ) [CRAN]
data.table (1.12.2  -> 1.13.0 ) [CRAN]
Matrix     (1.2-17  -> 1.2-18 ) [CRAN]

trying URL  'https://mran.microsoft.com/snapshot/2020-07-28/src/contrib/data.table_1.13.0.tar.gz'
Content type 'application/octet-stream' length 5273400 bytes (5.0 MB)
downloaded 5.0 MB

**Log Error**

ERROR
[0mError: package or namespace load failed for ‘data.table’ in library.dynam(lib, package, package.lib):
 shared object ‘datatable.so’ not found
Error: loading failed
Execution halted
 [91mERROR: loading failed
 [0m [91m* removing ‘/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/R/library/data.table’
 [0m [91m* restoring previous ‘/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/R/library/data.table’
 [0m [91mError: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package ‘data.table’ had non-zero exit status
Execution halted
 [0mThe command '/bin/sh -c R -e "library(checkpoint); snapshot_date <- tail(checkpoint::getValidSnapshots(), n = 1); setSnapshot(snapshot_date); install.packages(c('reticulate', 'remotes', 'e1071', 'optparse')); library(remotes); remotes::install_cran('azuremlsdk', upgrade = FALSE); remotes::install_version('xgboost'); remotes::install_github('Azure/azureml-sdk-for-r')"' returned a non-zero code: 1
2020/07/28 18:21:06 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: exit status 1
Run ID: ccn failed after 14m36s. Error: failed during run, err: exit status 1

**Comment by mx-iao** [comment]
Does it work on the compute instance when data.table gets upgraded?
btw, is there a reason why you are trying to move from working on the compute instance to a remote cluster run?

**Comment by harshbangad** [comment]
Tried to upgrade the packages on compute instance. Training was successful. But failed again on the compute cluster with same error.

The reason we are trying to do so is thinking in terms of long term architecture- 

1. Compute Instance- Load libraries and dataset. Create estimator and experiment . Create environment for compute cluster and inference cluster.
2. Compute cluster- Model Training- calling loaded libraries from compute instance.

Our understanding is that the compute instance needs to be the basic machine which controls the provisioning on the compute cluster and the compute cluster needs to be the powerful high resource box which starts and stops based on calls made by the instance.

3. Inference Cluster(Kubernetes service)- Model Scoring- Calling trained model object from compute cluster and score the new data. 
We use Data factory for ETL and orchestration for data currently. We plan to call the web service API in data factory pipeline for an automated system- to score new data as it comes in and write back to different sources.

We had this architecture discussion with some folks from MSFT and came down to this.
Let me know your thoughts or if we should re visit or modify this :)

**Comment by mx-iao** [comment]
Depending on the resource needs for your training scripts, you can also simply use your compute instance as the "workstation" where you do your model training, since when you go to create a compute instance you can pick the VM size (which enables you to select a more powerful machine for your needs). The benefits of doing this are that you do not have to configure a remote run, wait for the Docker image to build, and potentially deal with any issues that come up when moving from a local to remote run.

If you do your training locally on the compute instance and would also like to leverage Azure ML run tracking (where you can track the runs in ml.azure.com), you can use the interactive logging functionality: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-track-experiments#option-1-use-start_logging. The corresponding R SDK methods are [`start_logging_run()`](https://azure.github.io/azureml-sdk-for-r/reference/start_logging_run.html) and [`complete_run()`](https://azure.github.io/azureml-sdk-for-r/reference/complete_run.html)

Back to the original issue, if any of the CRAN packages you're trying to install have system dependencies, then you will have to create a custom Docker image for your remote run. Here is a related issue to that: #260

**Comment by harshbangad** [comment]
Thanks @mx-iao . Will try the docker, that was helpful. 

In case i trained the model on compute instance and have a saved model .rds file and want to score on that using AKS, will that work without docker?
While creating the AKS cluster, when i pass the same packages for scoring machine environment, wont we get the same error? 

When we call a scoring function script in the inference configuration, can we call more packages there and do some data cleansing as well right before just directly calling the data frame in JSON to predict? An example here-


Script for AKS-
pkg1 <- cran_package("caret")
pkg2 <- github_package("Azure/azureml-sdk-for-r")
r_env <- r_environment(name = 'signalz' 
                       ,cran_packages = list(pkg1),
                       ,github_packages = list(pkg2)  
                       
)
inference_config <- inference_config(
  entry_script = "ScoringFunction.R",
  environment = r_env)

aks_config <- aks_webservice_deployment_config(cpu_cores = 2, memory_gb = 10 )
aks_target <- create_aks_compute(ws, cluster_name = 'ScoringTest2')
wait_for_provisioning_completion(aks_target, show_output = TRUE)

aks_service <- deploy_model(ws, 
                            'aksservice', 
                            models = list(model), 
                            inference_config = inference_config, 
                            deployment_config = aks_config,
                            deployment_target = aks_target)
wait_for_deployment(aks_service, show_output = TRUE)

It fails with the message insufficient CPU. I tried to add more CPU and GPU, still got the same. Any way how to increase nodes in the R script?

The scoring script I am trying to call is as follows-

ScoringFunction.R

library(jsonlite)
library(azuremlsdk)

init <- function()
{
  model_path <- Sys.getenv("AZUREML_MODEL_DIR")
  model <- readRDS(file.path(model_path, "model_glm.rds"))
  message("logistic regression model loaded")
  ws <- load_workspace_from_config()
  ds <- get_datastore(ws,"johnstestdatastore")
  dset <- create_tabular_dataset_from_delimited_files(ds$path('Staged Data Zone/OpportunityScore/TestOpp.csv'), validate = TRUE,
                                                       include_path = FALSE, infer_column_types = TRUE,
                                                     set_column_types = NULL, separator = ",", header = TRUE,
                                                      partition_format = NULL)
  
   data <- dset$to_pandas_dataframe()

function(data)
  {
    vars <- as.data.frame(fromJSON(data))
    prediction <- predict(model, vars, type="prob")*100
    toJSON(prediction)
  }
}




FAILURE -
ERROR - Service deployment polling reached non-successful terminal state, current service state: Failed
Operation ID: 6ec5f52e-bd3a-4fac-8881-1682bd72edf2
More information can be found using '.get_logs()'
Error:
{
  "code": "KubernetesError",
  "statusCode": 400,
  "message": "Kubernetes Deployment Error",
  "details": [
    {
      "code": "Unschedulable",
      "message": "0/3 nodes are available: 3 Insufficient cpu."
    },
    {
      "code": "DeploymentFailed",
      "message": "Couldn't Schedule because the kubernetes cluster didn't have available resources after trying for 00:05:00."
    }
  ]
}

ERROR - Service deployment polling reached non-successful terminal state, current service state: Failed
Operation ID: 6ec5f52e-bd3a-4fac-8881-1682bd72edf2
More information can be found using '.get_logs()'
Error:
{
  "code": "KubernetesError",
  "statusCode": 400,
  "message": "Kubernetes Deployment Error",
  "details": [
    {
      "code": "Unschedulable",
      "message": "0/3 nodes are available: 3 Insufficient cpu."
    },
    {
      "code": "DeploymentFailed",
      "message": "Couldn't Schedule because the kubernetes cluster didn't have available resources after trying for 00:05:00."
    }
  ]
}

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  WebserviceException: WebserviceException:
	Message: Service deployment polling reached non-successful terminal state, current service state: Failed
Operation ID: 6ec5f52e-bd3a-4fac-8881-1682bd72edf2
More information can be found using '.get_logs()'
Error:
{
  "code": "KubernetesError",
  "statusCode": 400,
  "message": "Kubernetes Deployment Error",
  "details": [
    {
      "code": "Unschedulable",
      "message": "0/3 nodes are available: 3 Insufficient cpu."
    },
    {
      "code": "DeploymentFailed",
      "message": "Couldn't Schedule because the kubernetes cluster didn't have available resources after trying for 00:05:00."
    }
  ]
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Failed\nOperation ID: 6ec5f52e-bd3a-4fac-8881-1682bd72edf2\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"KubernetesError\",\n  \"statusCode\":

**Comment by mx-iao** [comment]
1. Resource issue - related topic [here](https://social.technet.microsoft.com/Forums/en-US/5760c135-6d29-41bb-a47c-e9ecbce59710/deploy-to-kubernetes-service-not-possible?forum=AzureMachineLearningService) and [doc on managing quota](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-manage-quotas)
2. Yes, AKS deployments are containerized. You will need to package the appropriate dependencies for your scoring script - e.g. through a custom Docker image.
3. I'm not sure I understand why you are trying to pass in a fixed data frame as the input to your web service. In general the expectation for deployed web services is that the user will hit the endpoint of your web service with some input, and then the input will be processed by the scoring function you've written in score.R. You can refer to the [Deploying models](https://azure.github.io/azureml-sdk-for-r/articles/deploying-models.html) vignette for a more detailed run through. The function returned by the `init()` method, the one defined as `function(data) { ... }`, is the scoring function that will be called each time the web service is consumed - so whatever input data the user provides to the web service endpoint is what gets passed to the `data` parameter of the scoring function. See here for more information on consuming webservices: https://azure.github.io/azureml-sdk-for-r/articles/deploying-models.html#consume-web-service.

**Comment by harshbangad** [comment]
Thanks @mx-iao . That was super helpful. Will try to build docker image for AKS as it does not like passing the packages through r-env and fails for AKS as well.

For point 3 and 4, lets say i have a data factory pipeline where I call a table from Azure SQL database. Now I want to pass that table as data frame to the script. So I should call that table in data factory pipeline and pass it to the web service. That will invoke the Score.R and pass the incoming data from pipeline to it within which i can perform feature engineering as well as prediction. 
And I do not make any data import call within the Score.R.
Is that correct?

**Comment by mx-iao** [comment]
@harshbangad Yes that sounds right. 
Btw, @lucazav wrote this article on creating custom Docker images that may be helpful for you: https://medium.com/microsoftazure/how-to-create-custom-docker-base-images-for-azure-machine-learning-environments-86aa4c7bc7b9

**Comment by harshbangad** [comment]
Thanks @mx-iao . That was super helpful .Great article @lucazav .

I have a question in general about architecture for inference cluster. Can we have multiple docker images on same inference cluster?
Lets say i have 20 different models. I want to run them on same inference cluster, as its easy for automation and maintenance.
But if a project needs different versions of R package, how do we manage that within same inference cluster? Is it possible ?

**Comment by mx-iao** [comment]
@harshbangad No you cannot have multiple Docker image per deployed web service - one web service maps to one deployment image and scoring file. However if you have a large enough inference cluster (assuming you mean AKS) you can probably deploy multiple web services to that cluster if there is adequate resources

**Comment by harshbangad** [comment]
@mx-iao I was able to follow the link to create a docker image.
https://medium.com/microsoftazure/how-to-create-custom-docker-base-images-for-azure-machine-learning-environments-86aa4c7bc7b9

I am getting error while publishing the image to azure container registry.
I followed the steps on https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-custom-docker-image#get-container-registry-information

This is the step it fails-
az acr build --image r-sdk-docker-img:v1 --registry zvosbx01dsml3592187b --file Dockerfile .
(Runnig it in command prompt after installing azure CLI)
Error- Unable to find Dockerfile

This is the image pushed on docker hub -
https://hub.docker.com/repository/docker/harshbangad/r-sdk-docker-img
( I used the same dockerfile from the article written by Lucazav above)

Login to azure/ docker and container was successful.

I believe i am missing one of the step where the Dockerfile can be found. I can see the file in r-sdk-docker-image folder in the compute instance. I tried to copy the file locally and specify the location as well

az acr build --image r-sdk-docker-img:v1 --registry zvosbx01dsml3592187b --file C:\Users\hbangad\Documents\Dockerfile .
Got this error- (Running as ADMIN)
Packing source code into tar to upload...
[WinError 5] Access is denied: '.\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5'


Please let me know if i am missing any step.

Dockerfile-
FROM mcr.microsoft.com/azureml/base:openmpi3.1.2-ubuntu16.04
RUN conda install -c r -y \
  r-essentials=3.6.0 \
  r-reticulate \
  rpy2 \
  r-remotes \
  r-rodbc \
  r-e1071 \
  r-optparse && \
  conda clean -ay && pip install --no-cache-dir azureml-defaults
RUN apt-get update && apt-get install -y \
  tzdata \
  zlib1g-dev && \
  apt-get clean

ENV TAR="/bin/tar"

# Set default locale
ENV LANG C.UTF-8

# Set default timezone
ENV TZ UTC

RUN R -e "remotes::install_github('https://github.com/Azure/azureml-sdk-for-r')"
RUN R -e "azuremlsdk::install_azureml(version = '1.10.0', remove_existing_env = TRUE)"



![image](https://user-images.githubusercontent.com/61249009/90455419-dde42500-e0aa-11ea-92cd-05da69391c15.png)

**Comment by mx-iao** [comment]
You need to navigate into the directory that contains the Dockerfile (or set the working directory accordingly)

**Comment by harshbangad** [comment]
Thanks @mx-iao . Keep getting these access denied errors even after running as Administrator.

![image](https://user-images.githubusercontent.com/61249009/90456163-0b31d280-e0ad-11ea-8353-fb10211e099b.png)
![image](https://user-images.githubusercontent.com/61249009/90456192-21d82980-e0ad-11ea-81ad-7f4fe272b622.png)

**Comment by mx-iao** [comment]
@harshbangad unfortunately this looks like a potential issue with Windows and not the R SDK. Another option you can do is use a compute instance to run the ACR commands to build the image. (you will have to upload your Dockerfile to your compute instance) - I usually just open a terminal via Jupyter to run my CLI commands

**Comment by harshbangad** [comment]
Thanks @mx-iao . Tried your suggestion on Jupyter terminal of the SSH enabled compute instance. 
Got an error on az acr login --name zvosbx01dsml3592187b
Looks like this an ongoing issue -
https://github.com/Azure/azure-cli/issues/13927

Have you encountered this or have any workaround suggestions?

The command failed with an unexpected error. Here is the traceback:

APIVersion 2019-12-01-preview is not available
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/acr/custom.py", line 243, in acr_login
    password=password)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 417, in get_login_credentials
    is_login_context=True)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 310, in _get_credentials
    registry, resource_group_name = get_registry_by_name(cli_ctx, registry_name)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/acr/_utils.py", line 107, in get_registry_by_name
    client = cf_acr_registries(cli_ctx)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/acr/_client_factory.py", line 19, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/mgmt/containerregistry/container_registry_management_client.py", line 208, in registries
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-12-01-preview is not available

**Comment by mx-iao** [comment]
Please track it with the issue you linked then as this appears to be a compute instance issue Azure/azure-cli#13927. You can try uninstalling and reinstalling the Azure CLI on the compute instance https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-azure-cli

Another workaround for now could be to use Docker Hub.

**Comment by harshbangad** [comment]
@mx-iao Is it necessary to build and publish the docker image on the container?

I am unable to use the azure CLI as it errors on both options- Terminal in compute insatnce with acr login and locally with access denied like i mentioned.

Can i use it if i am successfully able to push my docker image on azure container registry?

I used these commands and pushed the image on container, i also created a web app service for the container registry-
docker pull harshbangad/r-sdk-docker-img:v1
docker tag harshbangad/r-sdk-docker-img:v1 zvosbx01dsml3592187b.azurecr.io/dockertest:v1
docker login --username zvosbx01dsml3592187b.azurecr.io --password <password>
docker push zvosbx01dsml3592187b.azurecr.io/dockertest:v1

![image](https://user-images.githubusercontent.com/61249009/90854567-26f9da80-e332-11ea-813b-3e2a24df8213.png)

 Can i now use the image in azure ml to be deployed to a r_environment like this?

env <- r_environment("dock", custom_docker_image = "zvosbx01dsml3592187b.azurecr.io/r-sdk-docker-image:v1")
inference_config <- inference_config(source_directory = ".",
                                     entry_script = "ScoringFunctionData.R",
                                     environment = env)
local_deployment_config <- local_webservice_deployment_config(port = NULL)
local_service <- deploy_model(ws, 
                              'localpass', 
                              models = list(model), 
                              inference_config = inference_config, 
                              deployment_config = local_deployment_config)


The deploy_model command is taking forever to run. I am trying to understand if the push of image on container registry is enough to be used for any endpoint environment..

**Comment by mx-iao** [comment]
@harshbangad is your image on a private ACR? If so you will also need to provide the password details. You can see an example in the vignette in this pending PR: https://github.com/Azure/azureml-sdk-for-r/pull/379/files

Go to the section called "Create an Azure ML Environment" and the subsection "For ACR"

You can optionally use Docker Hub instead of ACR. If your Docker repo is public, all you will have to do is specify the docker image in the `custom_docker_image` parameter. See this vignette https://azure.github.io/azureml-sdk-for-r/articles/train-with-tensorflow.html for an example.

**Comment by mx-iao** [comment]
Btw, if you are using premium ACR you may hit a separate issue 'Unable to get image details: Authentication failed for Container Registry: aicenter.azurecr.io.' (from another customer: " we notice that is possible to authenticate using the token when we are in the Compute Instance, and locally but the experiment can't authenticate using the token in Compute Cluster, and we only run successfully when we have used the ACR admin user, but it's not reliable for others users")

And this is the explanation/mitigation for that issue:
"Customer is using private ACR feature that is fully supported by EMS and there are no issues on our side. The problem happens on premium ACR for non-admin users with repository-scoped access token for get manifest operation on which ACR returns 401. The feature itself is in Preview mode, that is stated on their doc page https://docs.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions.

Customer can mitigate the issue on their side, expanding the repository-scoped permissions"
