### ISSUE TITLE
invoke_webservice error in R sdk

### ISSUE THREAD

**Issue by coolkate3738** [Azure/azureml-sdk-for-r#367]
**Describe the bug**
Trying to call "invoke_webservice" in my gglasso model results in the following error:

> Error in UseMethod(\"predict\") : \n  no applicable method for 'predict' applied to an object of class \"c('gglasso', 'ls')

**To Reproduce**
I use matrix data format for the predict function.
I will start by providing my inference config script :
`#' Copyright(c) Microsoft Corporation.
#' Licensed under the MIT license.

library(jsonlite)
library(stats)

init <- function()
{
  model_path <- Sys.getenv("AZUREML_MODEL_DIR")
  model <- readRDS(file.path(model_path, "model_2019P01.rda"))
  message("lasso regression model loaded")
  
  function(data)
  {
    vars <- as.data.frame(fromJSON(data))
	prediction <- stats::predict(model,type="link",newx=vars)
    toJSON(prediction)
  }
}`

Then I do the following :
Take one row from model matrix and convert to data frame
`newdata = ((data.frame(X_holdout_model_matrix))[2,])`

Then call the web service : 
`pred <- invoke_webservice(aci_service, toJSON(newdata))`
`pred`

Error I am getting : 

> 
ERROR - Received bad response from service. More information can be found by calling `.get_logs()` on the webservice object. Error in py_call_impl(callable, dots$args, dots$keywords) : 
  WebserviceException: WebserviceException:
	Message: Received bad response from service. More information can be found by calling `.get_logs()` on the webservice object.
Response Code: 502
Headers: {'Connection': 'keep-alive', 'Content-Length': '121', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Thu, 30 Jul 2020 10:45:16 GMT', 'Server': 'nginx/1.10.3 (Ubuntu)', 'X-Ms-Request-Id': '275ae7a5-0403-469a-b6f2-5dd6b301305e', 'X-Ms-Run-Function-Failed': 'True'}
Content: b'Error in UseMethod("predict") : \n  no applicable method for \'predict\' applied to an object of class "c(\'gglasso\', \'ls\')"\n'
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Received bad response from service. More information can be found by calling `.get_logs()` on the webservice object.\nResponse Code: 502\nHeaders: {'Connection': 'keep-alive', 'Content-Length': '121', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Thu, 30 Jul 2020 10:45:16 GMT', 'Server': 'nginx/1.10.3 (Ubuntu)', 'X-Ms-Request-Id': '275ae7a5-0403-469a-b6f2-5dd6b301305e', 'X-Ms-Run-Function-Failed': 'True'}\nContent: b'Error in UseMethod(\"predict\") : \\n  no applicable method for \\'predict\\' applied to an object of class \"c(\\'gglasso\\', \\'ls\\')\"\\n'"
    }
}

Detailed traceback: 
  File "/databricks/conda/envs/databricks-ml/lib/python3.7/site-packages/azureml/core/webservice/aci.py", line 404, in run
    logger=module_logger)

ERROR - Received bad response from service. More information can be found by calling `.get_logs()` on the webservice object.
Response Code: 502
Headers: {'Connection': 'keep-alive', 'Content-Length': '121', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Thu, 30 Jul 2020 10:45:16 GMT', 'Server': 'nginx/1.10.3 (Ubuntu)', 'X-Ms-Request-Id': '275ae7a5-0403-469a-b6f2-5dd6b301305e', 'X-Ms-Run-Function-Failed': 'True'}
Content: b'Error in UseMethod("predict") : \n  no applicable method for \'predict\' applied to an object of class "c(\'gglasso\', \'ls\')"\n'

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  WebserviceException: WebserviceException:
	Message: Received bad response from service. More information can be found by calling `.get_logs()` on the webservice object.
Response Code: 502
Headers: {'Connection': 'keep-alive', 'Content-Length': '121', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Thu, 30 Jul 2020 10:45:16 GMT', 'Server': 'nginx/1.10.3 (Ubuntu)', 'X-Ms-Request-Id': '275ae7a5-0403-469a-b6f2-5dd6b301305e', 'X-Ms-Run-Function-Failed': 'True'}
Content: b'Error in UseMethod("predict") : \n  no applicable method for \'predict\' applied to an object of class "c(\'gglasso\', \'ls\')"\n'
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Received bad response from service. More information can be found by calling `.get_logs()` on the webservice object.\nResponse Code: 502\nHeaders: {'Connection': 'keep-alive', 'Content-Length': '121', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Thu, 30 Jul 2020 10:45:16 GMT', 'Server': 'nginx/1.10.3 (Ubuntu)', 'X-Ms-Request-Id': '275ae7a5-0403-469a-b6f2-5dd6b301305e', 'X-Ms-Run-Function-Failed': 'True'}\nContent: b'Error in UseMethod(\"predict\") : \\n  no applicable method for \\'predict\\' applied to an object of class \"c(\\'gglasso\\', \\'ls\\')\"\\n'"
    }
}

Detailed traceback: 
  File "/databricks/conda/envs/databricks-ml/lib/python3.7/site-packages/azureml/core/webservice/aci.py", line 404, in run
    logger=module_logger)

THen I get the logs : 

 `get_webservice_logs(aci_service, num_lines = 5000L)`
And get the following detailed logs :

> [1] "2020-07-30T10:26:34,272780713+00:00 - iot-server/run \n2020-07-30T10:26:34,272835014+00:00 - rsyslog/run \n2020-07-30T10:26:34,274785843+00:00 - gunicorn/run \n2020-07-30T10:26:34,277109477+00:00 - nginx/run \nEdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...\n2020-07-30T10:26:35,424982959+00:00 - iot-server/finish 1 0\n2020-07-30T10:26:35,437030137+00:00 - Exit code 1 is normal. Not restarting iot-server.\nStarting gunicorn 19.9.0\nListening at: http://127.0.0.1:31311 (9)\nUsing worker: sync\nworker timeout is set to 300\nBooting worker with pid: 44\nSPARK_HOME not set. Skipping PySpark Initialization.\nInitializing logger\n2020-07-30 10:26:36,247 | root | INFO | Starting up app insights client\nStarting up app insights client\n2020-07-30 10:26:36,247 | root | INFO | Starting up request id generator\nStarting up request id generator\n2020-07-30 10:26:36,247 | root | INFO | Starting up app insight hooks\nStarting up app insight hooks\n2020-07-30 10:26:36,247 | root | INFO | Invoking user's init function\nInvoking user's init function\n2020-07-30 10:26:36,312 | root | INFO | Users's init has completed successfully\nUsers's init has completed successfully\n2020-07-30 10:26:36,315 | root | INFO | Skipping middleware: dbg_model_info as it's not enabled.\nSkipping middleware: dbg_model_info as it's not enabled.\n2020-07-30 10:26:36,315 | root | INFO | Skipping middleware: dbg_resource_usage as it's not enabled.\nSkipping middleware: dbg_resource_usage as it's not enabled.\n2020-07-30 10:26:36,315 | root | INFO | Scoring timeout is found from os.environ: 60000 ms\nScoring timeout is found from os.environ: 60000 ms\n/opt/miniconda/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: lasso regression model loaded\n\n  warnings.warn(x, RRuntimeWarning)\n2020-07-30 10:26:49,861 | root | INFO | Swagger file not present\nSwagger file not present\n2020-07-30 10:26:49,862 | root | INFO | 404\n404\n127.0.0.1 - - [30/Jul/2020:10:26:49 +0000] \"GET /swagger.json HTTP/1.0\" 404 19 \"-\" \"Go-http-client/1.1\"\n2020-07-30 10:26:54,113 | root | INFO | Swagger file not present\nSwagger file not present\n2020-07-30 10:26:54,113 | root | INFO | 404\n404\n127.0.0.1 - - [30/Jul/2020:10:26:54 +0000] \"GET /swagger.json HTTP/1.0\" 404 19 \"-\" \"Go-http-client/1.1\"\n2020-07-30 10:27:20,317 | root | INFO | Validation Request Content-Type\nValidation Request Content-Type\n2020-07-30 10:27:20,317 | root | INFO | \tHost: localhost:5001\n\tHost: localhost:5001\n2020-07-30 10:27:20,317 | root | INFO | \tX-Real-Ip: 127.0.0.1\n\tX-Real-Ip: 127.0.0.1\n2020-07-30 10:27:20,317 | root | INFO | \tX-Forwarded-For: 127.0.0.1\n\tX-Forwarded-For: 127.0.0.1\n2020-07-30 10:27:20,317 | root | INFO | \tX-Forwarded-Proto: http\n\tX-Forwarded-Proto: http\n2020-07-30 10:27:20,318 | root | INFO | \tConnection: close\n\tConnection: close\n2020-07-30 10:27:20,318 | root | INFO | \tContent-Length: 51744\n\tContent-Length: 51744\n2020-07-30 10:27:20,318 | root | INFO | \tUser-Agent: python-requests/2.22.0\n\tUser-Agent: python-requests/2.22.0\n2020-07-30 10:27:20,318 | root | INFO | \tAccept: application/json\n\tAccept: application/json\n2020-07-30 10:27:20,318 | root | INFO | \tAccept-Encoding: gzip, deflate\n\tAccept-Encoding: gzip, deflate\n2020-07-30 10:27:20,318 | root | INFO | \tContent-Type: application/json\n\tContent-Type: application/json\n2020-07-30 10:27:20,318 | root | INFO | \tX-Ms-Request-Id: 6c0131d6-c289-4870-a046-ca2ed2978d71\n\tX-Ms-Request-Id: 6c0131d6-c289-4870-a046-ca2ed2978d71\n2020-07-30 10:27:20,318 | root | INFO | Scoring Timer is set to 60.0 seconds\nScoring Timer is set to 60.0 seconds\n/opt/miniconda/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error in UseMethod(\"predict\") : \n  no applicable method for 'predict' applied to an object of class \"c('gglasso', 'ls')\"\n\n  warnings.warn(x, RRuntimeWarning)\n2020-07-30 10:27:20,374 | root | ERROR | Encountered Exception: Traceback (most recent call last):\n  File \"/var/azureml-server/app.py\", line 225, in run_scoring\n    response = invoke_user_with_timer(service_input, request_headers)\n  File \"/var/azureml-server/app.py\", line 295, in invoke_user_with_timer\n    result = user_main.run(**params)\n  File \"/var/azureml-app/main.py\", line 21, in run\n    return_obj = driver_module.run(**arguments)\n  File \"/var/azureml-app/TEST_AML_KAT/_generated_score.py\", line 19, in run\n    dataR = r_run(input_data)[0]\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 178, in __call__\n    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 106, in __call__\n    res = super(Function, self).__call__(*new_args, **new_kwargs)\nrpy2.rinterface.RRuntimeError: Error in UseMethod(\"predict\") : \n  no applicable method for 'predict' applied to an object of class \"c('gglasso', 'ls')\"\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 1832, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 1818, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/var/azureml-server/app.py\", line 142, in score_realtime\n    return run_scoring(service_input, request.headers, request.environ.get('REQUEST_ID', '00000000-0000-0000-0000-000000000000'))\n  File \"/var/azureml-server/app.py\", line 238, in run_scoring\n    raise RunFunctionException(str(exc))\nrun_function_exception.RunFunctionException\n\nEncountered Exception: Traceback (most recent call last):\n  File \"/var/azureml-server/app.py\", line 225, in run_scoring\n    response = invoke_user_with_timer(service_input, request_headers)\n  File \"/var/azureml-server/app.py\", line 295, in invoke_user_with_timer\n    result = user_main.run(**params)\n  File \"/var/azureml-app/main.py\", line 21, in run\n    return_obj = driver_module.run(**arguments)\n  File \"/var/azureml-app/TEST_AML_KAT/_generated_score.py\", line 19, in run\n    dataR = r_run(input_data)[0]\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 178, in __call__\n    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 106, in __call__\n    res = super(Function, self).__call__(*new_args, **new_kwargs)\nrpy2.rinterface.RRuntimeError: Error in UseMethod(\"predict\") : \n  no applicable method for 'predict' applied to an object of class \"c('gglasso', 'ls')\"\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 1832, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 1818, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/var/azureml-server/app.py\", line 142, in score_realtime\n    return run_scoring(service_input, request.headers, request.environ.get('REQUEST_ID', '00000000-0000-0000-0000-000000000000'))\n  File \"/var/azureml-server/app.py\", line 238, in run_scoring\n    raise RunFunctionException(str(exc))\nrun_function_exception.RunFunctionException\n\n2020-07-30 10:27:20,375 | root | INFO | 500\n500\n127.0.0.1 - - [30/Jul/2020:10:27:20 +0000] \"POST /score HTTP/1.0\" 500 121 \"-\" \"python-requests/2.22.0\"\nException in worker process\nTraceback (most recent call last):\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 583, in spawn_worker\n    worker.init_process()\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/base.py\", line 134, in init_process\n    self.run()\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/sync.py\", line 124, in run\n    self.run_for_one(timeout)\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/sync.py\", line 83, in run_for_one\n    self.wait(timeout)\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/sync.py\", line 35, in wait\n    ret = select.select(self.wait_fds, [], [], timeout)\n  File \"/var/azureml-server/app.py\", line 265, in alarm_handler\n    raise TimeoutException(error_message)\ntimeout_exception.TimeoutException\nWorker exiting (pid: 44)\nworker timeout is set to 300\nBooting worker with pid: 66\nSPARK_HOME not set. Skipping PySpark Initialization.\nInitializing logger\n2020-07-30 10:28:21,190 | root | INFO | Starting up app insights client\nStarting up app insights client\n2020-07-30 10:28:21,190 | root | INFO | Starting up request id generator\nStarting up request id generator\n2020-07-30 10:28:21,190 | root | INFO | Starting up app insight hooks\nStarting up app insight hooks\n2020-07-30 10:28:21,190 | root | INFO | Invoking user's init function\nInvoking user's init function\n2020-07-30 10:28:21,222 | root | INFO | Users's init has completed successfully\nUsers's init has completed successfully\n/opt/miniconda/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: lasso regression model loaded\n\n  warnings.warn(x, RRuntimeWarning)\n2020-07-30 10:28:21,223 | root | INFO | Skipping middleware: dbg_model_info as it's not enabled.\nSkipping middleware: dbg_model_info as it's not enabled.\n2020-07-30 10:28:21,223 | root | INFO | Skipping middleware: dbg_resource_usage as it's not enabled.\nSkipping middleware: dbg_resource_usage as it's not enabled.\n2020-07-30 10:28:21,224 | root | INFO | Scoring timeout is found from os.environ: 60000 ms\nScoring timeout is found from os.environ: 60000 ms\n2020-07-30 10:45:16,671 | root | INFO | Validation Request Content-Type\nValidation Request Content-Type\n2020-07-30 10:45:16,671 | root | INFO | \tHost: localhost:5001\n\tHost: localhost:5001\n2020-07-30 10:45:16,672 | root | INFO | \tX-Real-Ip: 127.0.0.1\n\tX-Real-Ip: 127.0.0.1\n2020-07-30 10:45:16,672 | root | INFO | \tX-Forwarded-For: 127.0.0.1\n\tX-Forwarded-For: 127.0.0.1\n2020-07-30 10:45:16,672 | root | INFO | \tX-Forwarded-Proto: http\n\tX-Forwarded-Proto: http\n2020-07-30 10:45:16,672 | root | INFO | \tConnection: close\n\tConnection: close\n2020-07-30 10:45:16,672 | root | INFO | \tContent-Length: 51744\n\tContent-Length: 51744\n2020-07-30 10:45:16,672 | root | INFO | \tUser-Agent: python-requests/2.22.0\n\tUser-Agent: python-requests/2.22.0\n2020-07-30 10:45:16,672 | root | INFO | \tAccept: application/json\n\tAccept: application/json\n2020-07-30 10:45:16,672 | root | INFO | \tAccept-Encoding: gzip, deflate\n\tAccept-Encoding: gzip, deflate\n2020-07-30 10:45:16,672 | root | INFO | \tContent-Type: application/json\n\tContent-Type: application/json\n2020-07-30 10:45:16,672 | root | INFO | \tX-Ms-Request-Id: 275ae7a5-0403-469a-b6f2-5dd6b301305e\n\tX-Ms-Request-Id: 275ae7a5-0403-469a-b6f2-5dd6b301305e\n2020-07-30 10:45:16,672 | root | INFO | Scoring Timer is set to 60.0 seconds\nScoring Timer is set to 60.0 seconds\n/opt/miniconda/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error in UseMethod(\"predict\") : \n  no applicable method for 'predict' applied to an object of class \"c('gglasso', 'ls')\"\n\n  warnings.warn(x, RRuntimeWarning)\n2020-07-30 10:45:16,731 | root | ERROR | Encountered Exception: Traceback (most recent call last):\n  File \"/var/azureml-server/app.py\", line 225, in run_scoring\n    response = invoke_user_with_timer(service_input, request_headers)\n  File \"/var/azureml-server/app.py\", line 295, in invoke_user_with_timer\n    result = user_main.run(**params)\n  File \"/var/azureml-app/main.py\", line 21, in run\n    return_obj = driver_module.run(**arguments)\n  File \"/var/azureml-app/TEST_AML_KAT/_generated_score.py\", line 19, in run\n    dataR = r_run(input_data)[0]\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 178, in __call__\n    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 106, in __call__\n    res = super(Function, self).__call__(*new_args, **new_kwargs)\nrpy2.rinterface.RRuntimeError: Error in UseMethod(\"predict\") : \n  no applicable method for 'predict' applied to an object of class \"c('gglasso', 'ls')\"\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 1832, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 1818, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/var/azureml-server/app.py\", line 142, in score_realtime\n    return run_scoring(service_input, request.headers, request.environ.get('REQUEST_ID', '00000000-0000-0000-0000-000000000000'))\n  File \"/var/azureml-server/app.py\", line 238, in run_scoring\n    raise RunFunctionException(str(exc))\nrun_function_exception.RunFunctionException\n\nEncountered Exception: Traceback (most recent call last):\n  File \"/var/azureml-server/app.py\", line 225, in run_scoring\n    response = invoke_user_with_timer(service_input, request_headers)\n  File \"/var/azureml-server/app.py\", line 295, in invoke_user_with_timer\n    result = user_main.run(**params)\n  File \"/var/azureml-app/main.py\", line 21, in run\n    return_obj = driver_module.run(**arguments)\n  File \"/var/azureml-app/TEST_AML_KAT/_generated_score.py\", line 19, in run\n    dataR = r_run(input_data)[0]\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 178, in __call__\n    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 106, in __call__\n    res = super(Function, self).__call__(*new_args, **new_kwargs)\nrpy2.rinterface.RRuntimeError: Error in UseMethod(\"predict\") : \n  **_**no applicable method for 'predict' applied to an object of class \"c('gglasso', 'ls')**_**\"\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 1832, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 1818, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/var/azureml-server/app.py\", line 142, in score_realtime\n    return run_scoring(service_input, request.headers, request.environ.get('REQUEST_ID', '00000000-0000-0000-0000-000000000000'))\n  File \"/var/azureml-server/app.py\", line 238, in run_scoring\n    raise RunFunctionException(str(exc))\nrun_function_exception.RunFunctionException\n\n2020-07-30 10:45:16,731 | root | INFO | 500\n500\n127.0.0.1 - - [30/Jul/2020:10:45:16 +0000] \"POST /score HTTP/1.0\" 500 121 \"-\" \"python-requests/2.22.0\"\n"

It is also interesting because when I call the model (not using the web service , it works fine)
`json_test =toJSON(newdata)`
`vars <- as.data.frame(fromJSON(json_test))`
`prediction = stats::predict(cpm_model,type="link",newx=vars)`
`toJSON(prediction)`

> [[-0.3146]] 

**Expected behavior**
A prediction to be displayed in console without error

**Screenshots**

**Additional context**

**Comment by mx-iao** [comment]
Maybe you also have to explicitly load the library for the model itself in your scoring script: `library(gglasso)` https://stackoverflow.com/questions/38623624/usemethodpredict-no-applicable-method-for-predict-applied-to-an-object-o

**Comment by coolkate3738** [comment]
@mx-iao thank you for your response, 
Unfortunately it did not work , still see the following error : 

> [1] "2020-07-30T10:26:34,272780713+00:00 - iot-server/run \n2020-07-30T10:26:34,272835014+00:00 - rsyslog/run \n2020-07-30T10:26:34,274785843+00:00 - gunicorn/run \n2020-07-30T10:26:34,277109477+00:00 - nginx/run \nEdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...\n2020-07-30T10:26:35,424982959+00:00 - iot-server/finish 1 0\n2020-07-30T10:26:35,437030137+00:00 - Exit code 1 is normal. Not restarting iot-server.\nStarting gunicorn 19.9.0\nListening at: http://127.0.0.1:31311 (9)\nUsing worker: sync\nworker timeout is set to 300\nBooting worker with pid: 44\nSPARK_HOME not set. Skipping PySpark Initialization.\nInitializing logger\n2020-07-30 10:26:36,247 | root | INFO | Starting up app insights client\nStarting up app insights client\n2020-07-30 10:26:36,247 | root | INFO | Starting up request id generator\nStarting up request id generator\n2020-07-30 10:26:36,247 | root | INFO | Starting up app insight hooks\nStarting up app insight hooks\n2020-07-30 10:26:36,247 | root | INFO | Invoking user's init function\nInvoking user's init function\n2020-07-30 10:26:36,312 | root | INFO | Users's init has completed successfully\nUsers's init has completed successfully\n2020-07-30 10:26:36,315 | root | INFO | Skipping middleware: dbg_model_info as it's not enabled.\nSkipping middleware: dbg_model_info as it's not enabled.\n2020-07-30 10:26:36,315 | root | INFO | Skipping middleware: dbg_resource_usage as it's not enabled.\nSkipping middleware: dbg_resource_usage as it's not enabled.\n2020-07-30 10:26:36,315 | root | INFO | Scoring timeout is found from os.environ: 60000 ms\nScoring timeout is found from os.environ: 60000 ms\n/opt/miniconda/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: lasso regression model loaded\n\n  warnings.warn(x, RRuntimeWarning)\n2020-07-30 10:26:49,861 | root | INFO | Swagger file not present\nSwagger file not present\n2020-07-30 10:26:49,862 | root | INFO | 404\n404\n127.0.0.1 - - [30/Jul/2020:10:26:49 +0000] \"GET /swagger.json HTTP/1.0\" 404 19 \"-\" \"Go-http-client/1.1\"\n2020-07-30 10:26:54,113 | root | INFO | Swagger file not present\nSwagger file not present\n2020-07-30 10:26:54,113 | root | INFO | 404\n404\n127.0.0.1 - - [30/Jul/2020:10:26:54 +0000] \"GET /swagger.json HTTP/1.0\" 404 19 \"-\" \"Go-http-client/1.1\"\n2020-07-30 10:27:20,317 | root | INFO | Validation Request Content-Type\nValidation Request Content-Type\n2020-07-30 10:27:20,317 | root | INFO | \tHost: localhost:5001\n\tHost: localhost:5001\n2020-07-30 10:27:20,317 | root | INFO | \tX-Real-Ip: 127.0.0.1\n\tX-Real-Ip: 127.0.0.1\n2020-07-30 10:27:20,317 | root | INFO | \tX-Forwarded-For: 127.0.0.1\n\tX-Forwarded-For: 127.0.0.1\n2020-07-30 10:27:20,317 | root | INFO | \tX-Forwarded-Proto: http\n\tX-Forwarded-Proto: http\n2020-07-30 10:27:20,318 | root | INFO | \tConnection: close\n\tConnection: close\n2020-07-30 10:27:20,318 | root | INFO | \tContent-Length: 51744\n\tContent-Length: 51744\n2020-07-30 10:27:20,318 | root | INFO | \tUser-Agent: python-requests/2.22.0\n\tUser-Agent: python-requests/2.22.0\n2020-07-30 10:27:20,318 | root | INFO | \tAccept: application/json\n\tAccept: application/json\n2020-07-30 10:27:20,318 | root | INFO | \tAccept-Encoding: gzip, deflate\n\tAccept-Encoding: gzip, deflate\n2020-07-30 10:27:20,318 | root | INFO | \tContent-Type: application/json\n\tContent-Type: application/json\n2020-07-30 10:27:20,318 | root | INFO | \tX-Ms-Request-Id: 6c0131d6-c289-4870-a046-ca2ed2978d71\n\tX-Ms-Request-Id: 6c0131d6-c289-4870-a046-ca2ed2978d71\n2020-07-30 10:27:20,318 | root | INFO | Scoring Timer is set to 60.0 seconds\nScoring Timer is set to 60.0 seconds\n/opt/miniconda/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error in UseMethod(\"predict\") : \n  no applicable method for 'predict' applied to an object of class \"c('gglasso', 'ls')\"\n\n  warnings.warn(x, RRuntimeWarning)\n2020-07-30 10:27:20,374 | root | ERROR | Encountered Exception: Traceback (most recent call last):\n  File \"/var/azureml-server/app.py\", line 225, in run_scoring\n    response = invoke_user_with_timer(service_input, request_headers)\n  File \"/var/azureml-server/app.py\", line 295, in invoke_user_with_timer\n    result = user_main.run(**params)\n  File \"/var/azureml-app/main.py\", line 21, in run\n    return_obj = driver_module.run(**arguments)\n  File \"/var/azureml-app/TEST_AML_KAT/_generated_score.py\", line 19, in run\n    dataR = r_run(input_data)[0]\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 178, in __call__\n    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 106, in __call__\n    res = super(Function, self).__call__(*new_args, **new_kwargs)\nrpy2.rinterface.RRuntimeError: Error in UseMethod(\"predict\") : \n  no applicable method for 'predict' app

**Comment by mx-iao** [comment]
If there are any other packages your model depends on you will need to include those too (and make sure they are also in the inference environment) https://github.com/tidymodels/parsnip/issues/249

**Comment by coolkate3738** [comment]
@mx-iao  thank you so much, you are a star, I completely missed that, what a silly error, it works now that I included all the libraries in the inference script . Thank you again 👍
