### ISSUE TITLE
Segmentation fault error on calling get_workspace() in scoring function

### ISSUE THREAD

**Issue by Omi1906** [Azure/azureml-sdk-for-r#374]
Hi,

We are running into Fatal Python error : Segmentation fault on calling get_workspace() from init() scoring function and was hoping you could help us identify the problem.

**Implementation:** We have a trained model deployed to AKS cluster. We invoke the web service to call scoring function. For our scoring, we want to read data from datastore in azure ml workspace.

**Issue:** When trying to load workspace, the web service errors out with the following error: "Fatal Python error : Segementation fault"

**Probable cause:** So segmentation fault occurs when the memory is not accessible or data is not available. Based on the message, it looks like either we have some permission issue or problem with miniconda.

**Code excerpt(removed our piece):**

library(jsonlite)
library(azuremlsdk)
init <- function()
{
  model_path <- Sys.getenv("AZUREML_MODEL_DIR")
  model <- readRDS(file.path(model_path, "model_glm.rds"))
  message("logistic regression model loaded")
  function(data)
  {
    ws <- load_workspace_from_config(path = "./Complete",file_name = "config.json")
    vars <- as.data.frame(fromJSON(data))
    prediction <- predict(model, vars, type="prob")*100
    toJSON(prediction)
  }
}

**Partial Logs:**

2020-08-11 15:25:13,179 | azureml.core.run | INFO | Could not load the run context. Logging offline
\nCould not load the run context. Logging offline
\n2020-08-11 15:25:16,038 | azureml.core.run | INFO | Could not load the run context. Logging offline
\nCould not load the run context. Logging offline\n

**Fatal Python error:** Segmentation fault\n\nThread 0x00007f664b6ab700 (most recent call first):
\n  File \"/opt/miniconda/lib/python3.7/subprocess.py\", line 1611 in _try_wait
\n  File \"/opt/miniconda/lib/python3.7/subprocess.py\", line 1653 in _wait
\n  File \"/opt/miniconda/lib/python3.7/subprocess.py\", line 1019 in wait
\n  File \"/opt/miniconda/lib/python3.7/site-packages/azureml/dataprep/api/engineapi/engine.py\", line 87 in _wait_on_engine_death
\n  File \"/opt/miniconda/lib/python3.7/threading.py\", line 870 in run
\n  File \"/opt/miniconda/lib/python3.7/threading.py\", line 926 in _bootstrap_inner
\n  File \"/opt/miniconda/lib/python3.7/threading.py\", line 890 in _bootstrap

\n\nThread 0x00007f6624e0d700 (most recent call first):
\n  File \"/opt/miniconda/lib/python3.7/site-packages/azureml/dataprep/api/engineapi/engine.py\", line 111 in _enqueue_responses
\n  File \"/opt/miniconda/lib/python3.7/threading.py\", line 870 in run
\n  File \"/opt/miniconda/lib/python3.7/threading.py\", line 926 in _bootstrap_inner
\n  File \"/opt/miniconda/lib/python3.7/threading.py\", line 890 in _bootstrap

\n\nThread 0x00007f662260c700 (most recent call first):
\n  File \"/opt/miniconda/lib/python3.7/selectors.py\", line 415 in select
\n  File \"/opt/miniconda/lib/python3.7/socketserver.py\", line 232 in serve_forever
\n  File \"/opt/miniconda/lib/python3.7/threading.py\", line 870 in run
\n  File \"/opt/miniconda/lib/python3.7/threading.py\", line 926 in _bootstrap_inner
\n  File \"/opt/miniconda/lib/python3.7/threading.py\", line 890 in _bootstrap

\n\nCurrent thread 0x00007f6660217700 (most recent call first):
\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 106 in __call__
\n  File \"/opt/miniconda/lib/python3.7/site-packages/rpy2/robjects/functions.py\", line 178 in __call__
\n  File \"/structure/azureml-app/Complete/_generated_score.py\", line 19 in run
\n  File \"/var/azureml-app/main.py\", line 21 in run
\n  File \"/var/azureml-server/app.py\", line 296 in invoke_user_with_timer
\n  File \"/var/azureml-server/app.py\", line 226 in run_scoring
\n  File \"/var/azureml-server/app.py\", line 143 in score_realtime
\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 1818 in dispatch_request
\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 1832 in full_dispatch_request
\n  File \"/opt/miniconda/lib/python3.7/site-packages/flask/app.py\", line 2311 in wsgi_app
\n  File \"/var/azureml-server/appinsights/wsgi_wrapper.py\", line 24 in __call__
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/sync.py\", line 181 in handle_request
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/sync.py\", line 135 in handle
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/sync.py\", line 30 in accept
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/sync.py\", line 68 in run_for_one
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/sync.py\", line 124 in run
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/workers/base.py\", line 134 in init_process
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 583 in spawn_worker
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 616 in spawn_workers
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 545 in manage_workers
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 212 in run
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/app/base.py\", line 72 in run
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/app/base.py\", line 223 in run
\n  File \"/opt/miniconda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py\", line 61 in run
\n  File \"/opt/miniconda/bin/gunicorn\", line 8 in <module>\nworker timeout is set to 300
\nBooting worker with pid: 406\nInitialized PySpark session.\nInitializing logger

**Comment by mx-iao** [comment]
@Omi1906 I'm not sure I understand why you are trying to read data from your datastore from within the scoring script. In general the expectation for deployed web services is that the user will hit the endpoint of your web service with some input, and then the input will be processed by the scoring function you've written in score.R.

You can refer to the [Deploying models](https://azure.github.io/azureml-sdk-for-r/articles/deploying-models.html) vignette for a more detailed run through. The function returned by the `init()` method, the one defined as `function(data) { ... }`, is the scoring function that will be called each time the web service is consumed - so whatever input data the user provides to the web service endpoint is what gets passed to the `data` parameter of the scoring function. See here for more information on consuming webservices: https://azure.github.io/azureml-sdk-for-r/articles/deploying-models.html#consume-web-service.

If you are trying to use data in your datastore as input to the web service (basically input for your deployed model to make predictions on) then you should first deploy the web service, and then invoke that web service with the data from your datastore.

Please see the second half of this thread for more info on deployment best practices, super relevant to this issue: https://github.com/Azure/azureml-sdk-for-r/issues/365

**Comment by Omi1906** [comment]
@mx-iao Thank you for such a quick response and explanation. I had checked issue #365 and still had some questions though. Can you help me understand the reason why connecting to a datastore from within a scoring function is not a feasible architectural solution?

Let me explain our scenario. We work with SQL data which is in tabular format. We do our data extractions and transformations using Azure Data Factory. The end result is still in tabular format. Now the data passed to API call needs to in JSON format. This means a custom activity in Azure Data Factory which we will convert tabular data into JSON. We will get back our result in JSON format too which we have to convert back to tabular format.

This, for me, is an inefficient process as I have a way to connect to Azure ML datastore using R which allows me store, read, transform the data in any format needed. It is only that from within a scoring function I cannot do it.

I understand that the API call expects a parameter "data" in JSON format but we can ideally pass just a small JSON data e.g. [{1:1,2:1}] and then let R take care of actual prediction dataset within the scoring function.

**Comment by mx-iao** [comment]
If you want to access the data directly in the scoring script (which also means the data you can predict on is fixed to that datastore), is there any reason you are deploying a web service? What is the overall scenario you are trying to execute? The reason I'm asking is that our best practices for deployments is that the model gets deployed with a predict function, and anyone with access to the endpoint can invoke it with input that fits the expected schema. We do not typically see users try to access their workspace/fixed datastores in their scoring script. 

Can you run the `get_webservice_logs` method and get the logs from the service deployment?

**Comment by Omi1906** [comment]
The data in the scoring script will change even though the data store is same. Data store is a connection to Data Lake FileSystem. I can connect to any file in that data store. So every time we do scoring new data would be used for prediction. That enables anyone with access to the endpoint to invoke it with input that fits.

The reason to use webservice is so that we can use REST API to do the prediction. The API would be called in Azure Data Factory - Web Activity

Yes, the webservice gets deployed successfully. It is at the time of invoking the webservice we hit into the errors. I have sent the logs via email for your analysis.

**Comment by lucazav** [comment]
Hi @Omi1906 ,

did you try to:
1. Get your data from Data Lake directly into Azure Data Factory
2. Transform it in JSON format using [JSON Data Transformation](https://techcommunity.microsoft.com/t5/azure-data-factory/adf-adds-hierarchical-amp-json-data-transformations-to-mapping/ba-p/880516)
3. Call the web service passing your JSON string

In this way you'll have a "standard" web service that outputs predictions using any data as input, not only a given dataset into the Data Lake.

After that, if you really want to go on with the first solution, did you tried to get your workspace object using a service principal authentication? You can see how to do that in [this blog post](https://medium.com/microsoftazure/how-to-authenticate-into-azure-machine-learning-using-the-r-sdk-3ff930697bd1).

**Comment by Omi1906** [comment]
> Hi @Omi1906 ,
> 
> did you try to:
> 
> 1. Get your data from Data Lake directly into Azure Data Factory
> 2. Transform it in JSON format using [JSON Data Transformation](https://techcommunity.microsoft.com/t5/azure-data-factory/adf-adds-hierarchical-amp-json-data-transformations-to-mapping/ba-p/880516)
> 3. Call the web service passing your JSON string
> 
> In this way you'll have a "standard" web service that outputs predictions using any data as input, not only a given dataset into the Data Lake.
> 
> After that, if you really want to go on with the first solution, did you tried to get your workspace object using a service principal authentication? You can see how to do that in [this blog post](https://medium.com/microsoftazure/how-to-authenticate-into-azure-machine-learning-using-the-r-sdk-3ff930697bd1).

Thank you for your suggestions! We did think of using the Data Flow task but it feels like an unnecessary step when we can connect to a Datastore within our scripts.
We have a potential solution to use Docker file while deploying the webservice. I haven't tried it out yet, but will let you know.
