### ISSUE TITLE
Error while running the estimator setup

### ISSUE THREAD

**Issue by coolkate3738** [Azure/azureml-sdk-for-r#375]
**Describe the bug**
When specifying the estimator in R studio in AML I get the following error that has not happened before when I ran the same in Databricks
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7931437/90163356-e4faf280-dd8d-11ea-9708-4e81e0309ce7.png)

**Additional context**

**Comment by mx-iao** [comment]
What version of the R SDK are you using? You will need a more recent version of the Python SDK - the Python SDK version pinned to with the release on CRAN is old and doesn't have the required changes. You can install the R SDK from GitHub for your RStudio as that one is pinned a more recent version of the Python SDK.

**Comment by coolkate3738** [comment]
My version is 0.10.0, how can I specify version or upgrade it?

**Comment by mx-iao** [comment]
Can you run the following in your terminal:
`conda activate r-reticulate`
`pip list`
And see what version of the azureml-sdk (the python sdk) is installed?

Also, one thing - for specify cran packages you'll have to wrap it with the [ `cran_package()`](https://azure.github.io/azureml-sdk-for-r/reference/cran_package.html)

**Comment by coolkate3738** [comment]
Hi @mx-iao ,
I made it work, but when I tried making a suggested change for cran packages that you offered below I get the following error now :
![image](https://user-images.githubusercontent.com/7931437/90233423-0e5f6100-de16-11ea-9908-e7e87f5b190c.png)
 where previously this worked : 
`r_env <- r_environment(name = "cpm_env",
                      cran_packages = c("gglasso","futile.logger","jsonlite","dplyr","stringr","sparklyr","rlang","tidyr"))`

**Comment by mx-iao** [comment]
I don't think you are using an up to date version of the SDK from GitHub then.
Can you try reinstalling from GitHub.

**Comment by coolkate3738** [comment]
Hi @mx-iao  I have used the following commands to install the SDK : 
`nstall.packages("remotes")`
remotes::install_github('https://github.com/Azure/azureml-sdk-for-r', build_vignettes = TRUE)
azuremlsdk::install_azureml()`

I then ran the lines you mentioned above : 
`conda activate r-reticulate
pip list`

The sdk version I have : 

> azureml-sdk                          1.0.85

Then by trying to run this again  ; 
`r_env <- r_environment(name = "cpm_env",cran_packages=list(
  cran_package("gglasso"),
  cran_package("futile.logger"),
  cran_package("jsonlite"),
  cran_package("dplyr"),
  cran_package("stringr"),
  cran_package("sparklyr"),
  cran_package("rlang"),
  cran_package("tidyr"),
  cran_package("usethis"),
  cran_package("devtools")))`

and I get the same error : 

> Error in cran_package("gglasso") : could not find function "cran_package"

Could you please be able to point out where is the missing link as I did indeed install the SDK from github as you advised and it still seems to be outdated?

**Comment by mx-iao** [comment]
Please run `azuremlsdk::install_azureml(remove_existing_env = TRUE)` This should remove and install the python SDK  again

**Comment by coolkate3738** [comment]
thank you @mx-iao , this has been resolved with your last suggestion, I shall close the ticket
