### ISSUE TITLE
Failing When running R sdk experiment with databricks compute 

### ISSUE THREAD

**Issue by coolkate3738** [Azure/azureml-sdk-for-r#376]
**Describe the bug**
When I choose to run an R sdk estimator with Databricks attached compute it returns the error that this type of compute  is unsupported

**To Reproduce**
`est <- estimator(source_directory = ".",
                 entry_script = "modelling_aggregated_aml_tests.r",
                 script_params = list("--data_folder" = ds$path(target_path),
                                     "--config_folder" = ds$path(target_path_config),
                                      "--period" = period,
                                      "--train_pct" = train_pct_exp ),
                                        compute_target = compute_target,
                                        environment = r_env,
                                        custom_url_packages = ("./CPMDriversModelling/"))`

**Expected behavior**
A successful experiment run like with AML compute

**Screenshots**
This is my attached compute from Databricks : 
![image](https://user-images.githubusercontent.com/7931437/90253052-7626a380-de38-11ea-834b-27cc9e5dfbdd.png)

**Additional context**
This is the error I am getting when I run the experiment (fyi this runs successfully with AML cluster compute)

> Error in py_call_impl(callable, dots$args, dots$keywords) : TrainingException: TrainingException: Message: { "error_details": { "componentName": "execution", "correlation": { "operation": "c62773f091f52448bb2bd8a69026a2a5", "request": "e0d622de6f4f204f" }, "environment": "eastus", "error": { "code": "UserError", "message": "Unsupported compute target type Databricks" }, "location": "eastus", "time": "2020-08-14T13:10:18.7825226+00:00" }, "status_code": 400, "url": "https://eastus.experiments.azureml.net/execution/v1.0/subscriptions/066fc627-241c-4166-b66f-70f51b9b4b95/resourceGroups/CPM-PET-US-DEV-RG/providers/Microsoft.MachineLearningServices/workspaces/R_ML_WORKSPACE_DEV/experiments/CPM_EXPLORE/startrun?runId=CPM_EXPLORE_1597410613_6777a371" } InnerException ExperimentExecutionException: Message: { "error_details": { "componentName": "execution", "correlation": { "operatio

**Comment by mx-iao** [comment]
We don't support running on attached Databricks compute right now. Is there a reason you can't run the training code directly in Databricks rather than making it a remote run?

**Comment by coolkate3738** [comment]
Hi @mx-iao ,

Thank you for your response, 
I can run the code in databricks , but the business ask was to use AML in order to "encapsulate" our existing model to expose it as an API for the ability to call the model in order to make predictions based on the input. I hope that answers your question? 
Also, another reason that I am trying to make this work with databricks compute is because it would be much easier for me as I have my custom package installed on my Databricks compute and it currently works well that way, but if I try install a custom package as parth of the  "estimator" function in R SDK, it fails to actually work in my training script. Do you have any experience installing custom packages that then successfully get called in the training script?

**Comment by mx-iao** [comment]
Can you consider 1) training your model in Databricks and then 2) deploy your model with the AML R SDK? You will just need the model files for deployment

**Comment by coolkate3738** [comment]
@mx-iao  , 
thank you for your response.
So let me make sure I get this correctly.
1. No need to run experiment and train with AML
2. Just save model file .rda , .rds after trained in Databricks 
3. Ingest and register that model with AML 

If that is correct then I guess my question would be, how can I make the writing out and ingesting the model file as seamless as possible? Because we would usually grab the model file from the output folder of a run, so how can I write out using Databricks in a location that then AML can recognize ?

**Comment by mx-iao** [comment]
You can download the model to your local machine; and there is a `register_model()` https://azure.github.io/azureml-sdk-for-r/reference/register_model.html function you can use to register models from a local path

**Comment by coolkate3738** [comment]
Hi @mx-iao ,
Thank you for your response, sorry I was away on holiday so it took me a while to get back to you,
Unfortunately I think local machine is not an option here as we deploy everything using cloud + datalake for storage (if needed) as this is a specific model that will be used by the business.
