### ISSUE TITLE
Microsoft/Revo R Support? 

### ISSUE THREAD

**Issue by residentx10** [Azure/azureml-sdk-for-r#378]
**Is your feature request related to a problem? Please describe.**
No problems

**Describe the solution you'd like**
I'd like a solution like this "Azureml SDK for Microsoft R" 

**Describe alternatives you've considered**

**Additional context**
No additional images

**Comment by mx-iao** [comment]
This is not affiliated with Microsoft RevoScaleR nor do we have any official integrations. If you have questions for that product you can leave feedback there: https://docs.microsoft.com/en-us/sql/machine-learning/r/ref-r-revoscaler?view=sql-server-ver15
