### ISSUE TITLE
Times get converted to numpy datetime64 instead of Python datetime objects for TabularDataset filtering methods

### ISSUE THREAD

**Issue by mx-iao** [Azure/azureml-sdk-for-r#381]
For the `filter_dataset_before_time` method,
```
library(azuremlsdk)
ws = get_workspace('workspace-name')
mydate <- as.POSIXct("2011-05-01 17:55:23")
ds <- get_dataset_by_name(ws, 'test_date', version = "latest")
ds <- filter_dataset_before_time(ds, mydate)
```
the following error gets thrown:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : AttributeError: 'numpy.ndarray' object has no attribute 'microsecond'
```

Looks possibly related to this [issue](https://github.com/rstudio/reticulate/issues/198), where POSIXct time is getting automatically converted by reticulate to numpy `datetim64` objects rather than Python `datetime` objects, which is what is expected by the underlying Python SDK filter methods for TabularDatasets.

**Comment by diondrapeck** [comment]
The underlying Python function is expected a datetime.datetime object whereas reticulate converts R date-time objects to either datetime.date or np.datetime64. To bypass this, you can create a native Python datetime.datetime object with reticulate and pass that to `filter_dataset_before_time`.

Example, for the timestamp 2020-26-08 01:41:30:

```r
datetime <- import("datetime", **convert=FALSE**)

my_date <- datetime$datetime(2020L, 26L, 8L, 1L, 41, 30L)
filtered_ds <- filter_dataset_before_time(ds, my_date)
```
