### ISSUE TITLE
All or nothing data load flag

### ISSUE THREAD

**Issue by jakeatmsft** [Azure/azureml-sdk-for-r#392]
**Is your feature request related to a problem? Please describe.**
When loading a large dataset to dataframe using azuremlsdk to a local machine, the sdk will generate an out-of-memory exception if dataset is too large to read into memory.  Despite the error, the dataframe will still be loaded with a partial load without any indication that the data is incomplete.  Subsequent notebook code steps continue to run successfully on the incomplete data set.

**Describe the solution you'd like**
Either dataset load should be "all or nothing" or a flag should be available to ensure that full data set is loaded or dataframe will be empty.

**Additional context
Current method of loading dataset is using mount to local file system.

**Comment by diondrapeck** [comment]
@jakeatmsft - thanks for the feedback! The implementation of the dataset loading and memory handling is actually done by the main Python SDK; R SDK is simply providing a wrapper, so could you please report your feedback on [our main site](https://ml.azure.com/selectWorkspace?)? Click the smiley face on the top right hand side to open the feedback box.

Thanks!
