### ISSUE TITLE
Registering model throws error: "Error : C stack usage  644134250452 is too close to the limit"

### ISSUE THREAD

**Issue by Arincon** [Azure/azureml-sdk-for-r#404]
**Describe the bug**
When trying to register a model in Azure ML within an Azure Databricks Notebook, it immediately fails and gives the following error: "Error : C stack usage  644134250452 is too close to the limit".
This error is also thrown when I try to register a tabular dataset.

**To Reproduce**

1. Create cluster with Databricks Runtime 7.3 LTS version.
2. Install AzureML SKD from CRAN (or from GitHub, the error is the same).
3. Train a model.
4. Try to register the model with something like this:

registered_model <- register_model_from_run(run = run,
                                             model_name = "conversion_model",
                                             model_path = "modelo_gbm.zip")

**Expected behavior**
This should register the model in Azure ML as a new version of "conversion_model" model. This was working 2 or 3 months ago.

**Screenshots**
![image](https://user-images.githubusercontent.com/3784903/98531245-5dcff480-2280-11eb-9ea8-37409fcea412.png)

**Comment by adiazcan** [comment]
Hi! 
We think there is a bug in the R SDK for Azure ML because we changed the code to python and it run well with the rest of our training code in R

![image](https://user-images.githubusercontent.com/6652046/98584204-d3aa7f00-22c5-11eb-872f-e16318ba4c7a.png)

**Comment by diondrapeck** [comment]
@adiazcan - could you try updating to the latest github version of reticulate?
`remotes::install_github('https://github.com/rstudio/reticulate')`

**Comment by nihil0** [comment]
This worked for me. I was trying to call `azuremlsdk` code inside the `mcr.microsoft.com/azureml/base:openmpi3.1.2-ubuntu18.04` docker image. I don't get the C stack error anymore.
