### ISSUE TITLE
download_files_from_run throws C stack error

### ISSUE THREAD

**Issue by revodavid** [Azure/azureml-sdk-for-r#407]
**Describe the bug**
`download_files_from_run` and `download_file_from_run` throw an "C stack usage" error from R. This is indicative of an unchecked recursion loop.

**To Reproduce**
```
> download_files_from_run(run, prefix="outputs")
Error: C stack usage  1060675652244 is too close to the limit
```

**Expected behavior**
The download completes without error.

**Workaround**
Updating to the latest version of reticulate from github resolved this issue for me.

**Comment by diondrapeck** [comment]
Thanks for providing this workaround, @revodavid! I'll update the troubleshooting guide to include it.
