### ISSUE TITLE
How to use arguments with RScriptStep

### ISSUE THREAD

**Issue by samuda2019** [Azure/azureml-sdk-for-r#410]
**Describe the bug**
Followed through the documentation https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.r_script_step.rscriptstep?view=azure-ml-py to use RScriptStep

**To Reproduce**
step = RScriptStep(script_name='test.r',
                   name='test-step',
                   arguments=["--input", "testvalue"],
                   compute_target='cpu-cluster',
                   runconfig=rc,
                   source_directory='.')

**Expected behavior**
Would like to retrieve testvalue in args[1] within the test.r script. Is it expected to work similar to Python ScriptRunConfig class as below?

config = ScriptRunConfig(source_directory='.',
                            command=['python', 'train.py', '--arg1', arg1_val],
                            compute_target=cluster,
                            environment=env)

**Screenshots**

**Additional context**

**Comment by diondrapeck** [comment]
Hi @samuda2019 - no, RScriptStep is not similar to ScriptRunConfig. RScriptStep is part of the azureml.pipelines.steps module while ScriptRunConfig is part of the azureml.core module. RScriptStep is used to create one step of an experiment pipeline while ScriptRunConfig is used to create a single-standalone experiment.

Here's a link to the documentation for RScriptStep:
https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.r_script_step.rscriptstep?view=azure-ml-py

Arguments can be set this way:

```python

trainStep = RScriptStep(script_name="test.R",
                                      arguments=["--arg1", arg1_val],
                                      inputs=[...],
                                      outputs=[..],
                                      compute_target=compute_target,
                                      use_gpu=False,
                                      runconfig=rc,
                                      source_directory=project_folder)

```
