### ISSUE TITLE
DecodeError connecting to workspace

### ISSUE THREAD

**Issue by JamesHWade** [Azure/azureml-sdk-for-r#423]
**Describe the bug**
I am unable to connect to a workspace from RStudio within Azure Machine Learning.

**To Reproduce**
```r
library(azuremlsdk)
workspace = get_workspace(name = workspace_name, 
                          subscription_id = subscription_id,
                          resource_group = resource_group)
```

Error:
`DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().Error in value[[3L]](cond) : `

![image](https://user-images.githubusercontent.com/6314313/128512625-d15f4eb5-a35d-4ca4-a89d-919a68b824d8.png)
![image](https://user-images.githubusercontent.com/6314313/128512658-e863b774-e829-444d-aff6-280912f6578f.png)

**Comment by krisbock** [comment]
Hi @JamesHWade,  the Azure ML R SDK is being deprecated in favour of the new approach using the v2 CLI. See Interface to the Azure Machine Learning SDK • azuremlsdk for more details.

However, if you're set on the R SDK, can you upgrde the azuremlsdk version?  I can see you have the default installed version of azureml-sdk==1.10.  Please try activating the r-reticulate Conda environment and upgrading the sdk to >=1.18. So pip install azureml-sdk==1.18.

**Comment by joshkyh** [comment]
@krisbock suggestion worked for me. I am using Windows and yes, I also have azureml-sdk==1.10

If you need more details:
run this in R
reticulate:::py_config()

Find out your r-reticulate environment location.

Open CMD, cd C:/Users/jkim.HCI/Documents/.conda/envs/r-reticulate

python.exe -m pip install azureml-sdk==1.18
